alphagov/paas-team-manual

- docs/team/working_practices.md
So that multiple people don't duplicate effort by reviewing the same PR.
> [#108440080] Assign pull request to yourself when reviewing

- docs/team/orientation.md
Some key information to help new starters to find their way.
Particularly interested in feedback from people that have joined more recently: @Jonty @combor @alext @timmow - is this useful?
> [#108440080] Orientation repos/events/URLs

- docs/guides/spruce.md
Story: https://www.pivotaltracker.com/story/show/108866238
As an output of the story we created a spruce tutorial, based on spruce PR https://github.com/geofffranks/spruce/pull/69
The content of the tutorial was already reviewed by @keymon. Now we capture it in the team manual.
The spruce PR should be merged soon, but the instructions still depend on it. So this guide should be edited later.
* Check for any critical errors or inconsistencies
Anyone but @saliceti, @jimconner
> [#108866238] Add guide/spruce.md from spike outputs

- docs/team/working_practices.md
Which helps other members of our team review pull requests. This was an
action from the retrospective on 2016-01-12.
> Document the template we use for pull requests

- docs/team/orientation.md
**Please do not merge** - this is incomplete change. I'm hoping for corrections, discussion and contributions to fill the blanks.
Create a list of things that will help a new starter to the team learn about
the tech we use. Written for someone who has experience running infrastructure,
but hasn't used the particular tools we use. (eg. me)
Since markdown tables are pretty horrid to read in plain text, you'll likely want to click on "Files changed", then View to see rendered markdown.
> Guidance for learning about tech we use

- docs/team/working_practices.md
Describe why commit messages are more important than pull request
descriptions, but that it's perfectly OK to copy the contents of commit
messages to form PR descriptions.
https://twitter.com/dancarley/status/449164320321310720
> Commit messages are more important than PRs descs

- docs/styleguides/YAML.md
- docs/styleguides/concourse_pipeline.md
- docs/styleguides/index.md
Add some team-specific styleguides.
This is very much a first pass to get something down. The items captured here came from alphagov/paas-cf#138. Some of them are still being discussed amongst the team.
Discuss, debate etc.
Everyone on the team, although I propose that this should be left to @dcarley to merge as Tech Lead.
> Styleguides Straw man

- docs/architecture_decision_records/ADR005-pingdom-healthchecks.md
We want to record why we made the applications on the staging environment accessible from the outside world and why we proposed to remove the CI healthchecks in Pingdom.
See [#115347323](https://www.pivotaltracker.com/story/show/115347323)
Read it. Make sure it makes sense.
Anyone but me
> [#115347323] ADR for making staging accessible from everywhere

- docs/team/working_practices.md
Update to team manual to describe pull request template
Read through changes either in PR, or run locally
Anyone but Rory
> Changes to working practices to clarify how spikes should be handled

- docs/guides/GPG.md
- docs/team/working_practices.md
This covers how we are going to GPG sign PR merges.
> [#117605669] Add documentation about GPG signing merge commits.

- docs/team/working_practices.md
It was unclear for me what n is for `make merge_pr PR=<n>`. Apart from
that I fixed few typos and removed white spaces at the end of some
lines.
Check if my changes make sense. 
Not me.
> Add info about what N is for merge_pr

- docs/team/upgrading_cloud_foundry.md
Details on updating cloud foundry from Pivotal Story: https://www.pivotaltracker.com/story/show/116983391
> include details for upgrading cloud foundry

- docs/architecture_decision_records/ADR007-terminating-tls-at-elbs.md
I picked ADR007 because it was available and roughly the correct cronology.
> Document why we placed ELBs in front of everything

- docs/architecture_decision_records/ADR010-postgres-bind-behaviour.md
> Add ADR regarding the postgres broker credentials.

- .gitignore
- docs/team/dashboard_mac_mini.md
Give more details about how to get access to the mac mini.
Give urls for all the pages it currently displays.
> Update mac mini page

- docs/architecture_decision_records/ADR003-AWS-credentials.md
- docs/architecture_decision_records/ADR004-domain-naming-scheme.md
- docs/architecture_decision_records/ADR007-terminating-tls-at-elbs.md
- docs/architecture_decision_records/ADR008-haproxy-for-request-rewriting.md
- docs/guides/CloudFoundry_debugging.md
- docs/guides/GPG.md
- docs/guides/spruce.md
- docs/styleguides/YAML.md
- docs/team/working_practices.md
Just some refinements to be more explicit.
Especially helpful for new starters, but also it's good to document our
current practice, rather than a historical or idealistic version of it.
`mkdocs serve` and friends as per the README.
Visit `localhost:8000` and make sure the changed page makes better sense than before.
Anyone but @benhyland
> Improve docs on merging PRs and forking

- docs/architecture_decision_records/ADR013-building-bosh-releases.md
We completed the spike to decide the approach, so we should
record the decision in our team docs.
This ADR only records the basic decision, and could be updated with
more details as we actually apply the approach.
See https://www.pivotaltracker.com/n/projects/1275640/stories/128937731
Anyone can review.
> [#128937731] Add ADR for building bosh releases

- docs/team/networking_in_aws.md
Derived from notes I've made as I've been learning what
AWS does and how we use it.
I think this could be useful for others, especially new starters,
and is at a high enough level to not go instantly out of date.
To review:
Decide if the doc is useful.
If it is, check carefully for inaccuracies.
Also check for statements which might change soon or often - these should be avoided in docs which aren't tested or generated.
> Add overview of our AWS network layout

- docs/team/dashboard_mac_mini.md
It's on a different network.
Also give more specific instructions on how to use screen sharing.
> Update mac mini advice to mention the new machine

- docs/team/responding_to_security_issues.md
As part of [#132677645](https://www.pivotaltracker.com/n/projects/1275640/stories/132677645) this documents how we should respond to security issues.
> Add documentation on responding to security issues

- docs/guides/common_support_tasks.md
This is likely to become a regular support task; let's mention that
the script exists.
See https://github.com/alphagov/paas-cf/pull/626 and https://www.pivotaltracker.com/story/show/130821719
> [#130821719] Docs for user research org cleanup

- docs/guides/locking_users.md
Story: [Investigate "dead souls" on the platform](https://www.pivotaltracker.com/story/show/136250789)
Describe how to disable user accounts on PaaS and communicate with org
managers to see what's to be done.
* Check the text makes sense
* Check the process works as expected.
Not @mtekel or me
> [#136250789] Disabling user accounts

- docs/guides/IPSec_debugging.md
We're about to implement the IPSec encryption, between some of our nodes. It may so happen, that one will be in need of debugging the IPSec connectivity. Wrong time in the wrong place, I suppose.
In order to make their task simpler, we'd like to document some of the techniques we've used while implementing the IPSec.
Read through the docs and see if these make any sense...
Not @mtekel or @paroxp
> [#136558969] Add IPSec debugging guide

- docs/guides/IPSec_debugging.md
Follow up to discussion https://github.com/alphagov/paas-team-manual/pull/84#issuecomment-271840064 
I found this command quite useful when debugging IPSEC so let's add it to the team manual.
Not @combor
> [#136558969] Add a tcpdump command that filters IPSEC

- docs/team/working_practices.md
We agreed on 13th December that we should document that:
- Part of approval is ensuring that follow-up work is scheduled
- Definition of done should include keeping users informed about changes
Anyone but @bleach
> Updates from retro

- docs/team/pagerduty.md
Story: [Configure schedules and escalation policies for PagerDuty](https://www.pivotaltracker.com/story/show/135953741)
PagerDuty manual setup and basic operations. It may be improved over time.
* Does it make sense?
* Should it cover more?
* Does it look pretty?
Not me
> [#135953741] Guide for PagerDuty

- docs/team/orientation.md
We've moved the documentation off RTD onto the PaaS.
Check the new link content matches that of the old link.
You!
> Update documentation URL's now we've moved off RTD

- docs/architecture_decision_records/ADR017-cell-capacity-assignment.md
[Write ADR for cell capacity assignment](https://www.pivotaltracker.com/n/projects/1275640/stories/133433215)
Write up in the form of ADR what we have decided for cell memory capacity
management. In short: keep 50% of reserved org memory available when a zone
fails.
Proofread and fact-check.
not @mtekel
> [#133433215] Describe cell capacity assignment

- docs/support/escalation.md
- docs/support/support_manual.md
This is a placeholder for new support section that will in the future
contain info related to our support processes. Now it has only two
sub-sections pointing to google docs.
Sanity check
Not me
> [#135954607] Add support section

- docs/team/rotating_credentials.md
Document how to rotate credentials using the tasks introduced in https://github.com/alphagov/paas-cf/pull/802
Proofread. Check it makes sense.
not @mtekel
> [#130020741] Document how to rotate credentials

- docs/guides/Documentation_system.md
Update the docs to make it clear that the deployment should be automatic and also that we've finished our migration now.
Read the words what I wrote and confirm they can be parsed by humans & agree with reality.
Anyone but me. Possibly @Jonty would be interested?
> Update tech docs deployment guide

- docs/support/responding_to_alerts.md
Story: [Create alerts for anomalous UAA behaviour](https://www.pivotaltracker.com/story/show/134579301)
Help to diagnose brute force attacks by looking at UAA logs.
Not me
> [#134579301] Add support security section

- docs/guides/CloudFoundry_debugging.md
Add information about how to find out which cell an application instance is
running on. This came up in Slack this morning, with thanks to @saliceti and
@davidillsley.
See if it makes sense. Try out the commands.
Not @dcarley
> CF debugging: Which cell is my app running on?

- docs/support/finding_activity.md
We'd like to show we can investigate the activity of a user whose credentials have been compromised.
- Read through the content
- Apply instructions and attempt perform little investigation
Not @paroxp
> [#143024609] Document the way of finding user activity

- docs/support/responding_to_alerts.md
To support the new monitors added in alphagov/paas-cf#881
Check that the text makes sense and is useful.
Not @dcarley
> [#141315433] Responding to alerts: CPU credits

- docs/architecture_decision_records/ADR019-accessing-user-provided-services.md
Jotted down an overview of what I think are the three main options for helping
a currently onboarding service access their hosted services.
This is to share with that team and also get an initial review from tech leads
* Read, and verify it makes sense, and matches what we have decided.
* Optionally: squash down some of the commits before merging.
@dcarley @henrytk @timmow
> [#142066597] ADR for accessing user provided services in AWS

- docs/support/responding_to_alerts.md
We've added a new alert to detect when concourse needs shaking, this documentation is to be linked from the alert.
> [#144515851] Add documentation on shaking concourse, to be linked from alerts.

- docs/guides/enhancing_kibana.md
- docs/support/finding_activity.md
We'd like to debug Cloud Foundry components during or after an incident.
It may help, if we had a goto guide on both searching and creating new
parsed access logs.
Read through the docs, perhaps try adapting them yourself.
Neither @saliceti nor myself.
> [#144690295] Add tips and guides on access logs

- docs/team/notifying_tenants.md
I've added new incident response templates: 
- we're having an incident
- update during an incident
- further update during an incident
- we've resolved the incident
Read the templates and check for errors/typos etc.
Not me
> Notifying tenants content edits

- docs/guides/upgrading_CF,_bosh_and_stemcells.md
These two releases have been superseded.
Check the links work and the releases are the correct ones.
Anyone but me or @combor
> [#145682111] Update Bosh release URLs

- docs/guides/upgrading_CF,_bosh_and_stemcells.md
Multiple CF upgrades have now ran into problems with Datadog monitors
being broken.
Proofread and check it makes sense.
Anyone but me
> [#145682111] Update CF upgrade docs for Datadog

- docs/team/our_orgs_on_the_paas.md
We've done some work to rationalise the orgs we use on the platform. This documents that decision, and the rationale behind it.
Read, check it makes sense.
> [#148289089] Document how we use orgs on the PaaS.

- docs/architecture_decision_records/ADR020-deletion_of_ci_environment
This ADR  explains why we decided to delete CI env, keep staging and
separate build CI
Read the content and decide if it's sane.
Not @combor
> [#149566861] ADR020: deletion of CI environment

- docs/team/working_practices.md
As a team we are no longer using this.
> Remove references to Pair Stair

- docs/guides/CF_UAA_user_management.md
Replaces the previous instructions that were quite difficult to use.
Review with alphagov/paas-cf#1051
Anyone.
> [#149929104] Reference new uaa_lock_user.rb script

- docs/support/responding_to_alerts.md
We'd like to keep our process the same for each of interactions on this
topic. These sections will be linked to from Datadog alerts for person
on support to have a quick reminder of our procedures.
- Sanity check
- Run the command in question
To be tested/merged with alphagov/paas-cf#1071
Neither @46bit nor myself.
> [#147674123] Document the response to RDS events

- docs/architecture_decision_records/ADR443-ssl-only-for-applications-and-cf-endpoints.md
- docs/architecture_decision_records/ADR444-redirect-http-for-applications.md
For discussion/review only at this stage:
Add an ADR describing the decision to redirect http app traffic to https.
> [#139841751] Add ADR for decision to redirect http app traffic.

- docs/guides/upgrading_CF,_bosh_and_stemcells.md
- docs/team/notifying_tenants.md
Now that we've separated these out from cf-release, we need to capture
how/when we upgrade these.
Read, check it makes sense in the context of https://github.com/alphagov/paas-cf/pull/1085.
Not me.
> [#145695325] Add notes on upgrading buildpacks.

- docs/guides/Restoring_the_CF_databases.md
- docs/support/support_manual.md
- docs/team/notifying_tenants.md
Fixes a couple of issues with internal links:
* Use relative links everywhere.
* Fix a link to the incident comms section
See commits for details
Run locally as described in the README. Verify the updated links work.
Not me.
> Fix some links

- docs/architecture_decision_records/ADR022-web_app_language_and_framework_selection.md
Fix some gramatical issues found in #165 
* Read
* Check my grammar
Not me.
> Fix a couple of gramatical issues

- docs/team/working_practices.md
Added in tech docs changes-specific content to working practices section.
> Add Tech Docs Changes to section

- docs/guides/releasing_bosh_blobs.md
We had to add a new release blob to a service broker but we had authentication problems with the BOSH cli. We documented the process so others have clear instructions how to do this.
Read through the guide and check for spelling mistakes.
Not @bandesz
> Add guide for releasing BOSH blobs

- docs/support/finding_activity.md
Add notes about how to find gorouter stdout and stderr logs.
Read it, check the formatting.
Not @bandesz
> [#153367232] Add notes about gorouter stdout and stderr logs

- docs/architecture_decision_records/ADR023-idle-cpu-alerting-change.md
Recorded the idle CPU monitoring change as ADR023. This change was made during the implementation of ADR021.
Run locally with `mkdocs serve` as per README and verify content.
Not @LeePorte
> [#153247126] Added ADR023 for CPU monitoring change

- docs/team/dashboard_mac_mini.md
This replaces the paas-dashboard app. We also haven't been using
Automator for a long time.
Proofread and check the link works.
Anyone but me.
> [#152539815] Update docs on Datadog triggered monitors

- docs/team/rotating_credentials.md
Proofread. Review in conjunction with https://github.com/alphagov/paas-cf/pull/1174
Anyone but me, @chrisfarms, or @46bit
> [#143584125] Add instructions for rotating SMTP credentials

- docs/support/responding_to_alerts.md
- docs/team/rotating_credentials.md
Proofread.
Review in conjunction with related pull request on paas-cf: https://github.com/alphagov/paas-cf/pull/1180
Anyone but me or @46bit
> [#146463199] CDN certificate monitoring guidance

- docs/team/tenant_personal_data.md
Link to subject access request docs
Ensure the text of this change and the linked document make sense to you. Fire any queries to @urmishah 
Not @bleach or @urmishah
> Link to subject access request docs

- docs/support/responding_to_alerts.md
We no longer use purchased certificates, we use ACM.
Anyone but me.
> [#154959067] Update certificate guidance

- docs/support/responding_to_alerts.md
[#155178552 Monitor Redis queue length for ELK stack](https://www.pivotaltracker.com/story/show/155178552)
What?
----
We added the monitoring of the Redis LogSearch queue size in [1]
and we want to document how to respond to this alert.
[1] https://github.com/alphagov/paas-cf/pull/1235
How to review?
-------
proof reading
Who?
----
Anyone but me
> [#155178552] Document how to respond to LogSearch queue alert

- docs/guides/Connecting_to_Concourse_and_BOSH.md
- docs/guides/releasing_bosh_blobs.md
- docs/support/responding_to_alerts.md
Update docs to use Bosh CLI v2 commands, update SSH instructions
Check it locally
Not @chrisfarms or me
> [#154437854] Update docs to use Bosh CLI v2 commands, update SSH instructions

- docs/guides/CF_UAA_user_management.md
We no longer have a separate Gemfile for the scripts directory[1]. This
updates the insteuctions here accordingly.
[1]https://github.com/alphagov/paas-cf/commit/42e9fc88e6bc812a36dfeb3890e5373320170d58
> [Support] Update UAAC instructions for new Gemfile layout

- docs/team/rotating_credentials.md
As introduced in alphagov/paas-cf#1292
Test with alphagov/paas-cf#1292
The same person as alphagov/paas-cf#1292
> [#155854402] Document cert rotation

- source/architecture_decision_records/ADR022-web_app_language_and_framework_selection.html.md.erb
- source/architecture_decision_records/ADR024-web-app-language-and-framework-selection-2.html.md.erb
- source/index.html.md.erb
We've chosen to go with node for PaaS Admin tool. This should be
recorded for historical references along with the reasoning behind the
decision.
- Read through the content and make sure it's sensible
> Amend the previous ADR022

- source/guides/upgrading_CF,_bosh_and_stemcells.html.md.erb
What
---
We are now using cf-deployment and separate buildpack upgrades from
CF upgrades.
How to review
---
Proofread.
Who
---
Anyone but me or @bandesz
> [#156804143] Upgrade docs on CF upgrades

- source/support/responding_to_security_issues.html.md.erb
So that people can understand what they are because:
- IA has other meanings such as Information Architecture
- CO and SIRO aren't commonly used
Check that it makes sense.
Anyone.
> Expand IA and CO SIRO acronyms

- source/support/incident_process.html.md.erb
See diff. 
Pivotal: https://www.pivotaltracker.com/story/show/157735425
> [#157735425] Update incident instructions

- source/support/roles_and_responsibilities.html.md.erb
See diff.
Pivotal story (not public): https://www.pivotaltracker.com/story/show/148742947
> [#148742947] Add support details for Bank Holiday cover

- source/team/working_practices.html.md.erb
To reflect the fact that:
- review and approval can be done by the same person
- we no longer have a Business Analyst
- we have Feature Leads
- we haven't been using work in progress limits
- names on stories indicate availability of work
I've collapsed some of the existing content together as a result.
Check that it makes sense and reflects reality.
Anyone.
> Update story process

- source/architecture_decision_records/ADR027-pipeline-locking.html.md.erb
- source/index.html.md.erb
Pivotal story (non-public): https://www.pivotaltracker.com/story/show/116962415
Proofread. Make sure it makes sense and reflects our decision and the implications. You can run it locally to check the link.
Anybody but me
> [#116962415] ADR027 - Pipeline locking

- source/support/support_manual.html.md.erb
- source/team/dashboard_mac_mini.html.md.erb
Remove mentions of Grafana and Graphite as we removed these services.
Code review.
Not me.
> [#156368115] Remove mentions of Grafana and Graphite

- source/support/support_manual.html.md.erb
See commit message.
Code review. Check the link works.
Not @46bit
> Put London staging and prod pipelines on dashboard

- .circleci/config.yml
- .travis.yml
We've found Travis can take ages to build. This therefore replaces Travis with CircleCI.
Look over the config. Checkout the build on CircleCI...
Not me.
> [Firebreak] Replace Travis with CircleCI

- source/guides/upgrading_CF,_bosh_and_stemcells.html.md.erb
What?
-----
Add more info regarding update the submodule and things to check in
the manifest.
How to review?
------
proof reading
Who?
---
Not me
> [#158938536] Update cf-upgrade guide with more details

- source/architecture_decision_records/ADR028-move-logs-to-logit.html.md.erb
- source/index.html.md.erb
Add ADR028 - the Decision to continue moving platform logs to Logit.io
Proofread. Make sure it makes sense and reflects our decision and the implications. You can run it locally to check the link is correct.
Anybody but me
> ADR028 - decision of moving platform logs to logit

- source/index.html.md
- source/support/rsyslog.html.md
What
----
Mostly so the information on
https://www.pivotaltracker.com/story/show/159559834 is in a more obvious
place. I've provided far less detail in these docs than there is on the
ticket as the team manual really is a higher level thing.
How to review
-------------
Check the docs make sense / are at the right level for the team manual
audience.
Who can review
--------------
Anyone other than @richardTowers
> [#159559834] - Add a section on investigating rsyslog issues

- source/guides/editing_logstash_filters.html.md
- source/index.html.md
What
----
This PR adds the process for creating repeatable logit filters form
the code in our pipeline. This is stored in source control and by using
the supplied script creates repeatable results from this input.
How to review
-------------
Follow the process in this PR
Who can review
--------------
Not @LeePorte, @blairboy362 and @samcrang
> [#157053149] Add process for updating filters in logit

- source/index.html.md
- source/support/restoring_elasticsearch_backups.html.md
What
----
As we are moving into public beta for Aiven it is sensible to capture
how backups are restored. In this case we are performing a support
conduit to Aiven as there is no method in either the UI or API to
perform restoration.
How to review
-------------
Code review
Who can review
--------------
Not @LeePorte
> Add Elasticsearch backup restoration information

- .gitignore
- source/guides/trial_accounts.html.md
- source/index.html.md
What
----
We are now enforcing the 3 month period of trial accounts. this commit
adds a process that we can follow for repeatable results in collating
the data and contacting the org managers.
How to review
-------------
Run locally and follow the process that is documented up until contacting the org managers.
You will need paas-cf branch add-quota-to-org-usage
Who can review
--------------
Not @LeePorte
> [#160342179] Add process for trial and abandoned accounts

- source/incident_management/incident_process.html.md
* re-order who to escalate to: Head of Reliability Engineering first
* fix broken unordered list. They were displaying inline for some
reason, switching dashes to asterisks fixed it.
* removed trailling whitespace
How to review
-------------
I am merging this without review.
> [#159887346] A couple of tweaks:

- source/architecture_decision_records/ADR030-single-staging-london.html.md
- source/index.html.md
New ADR to document the rationale for running a single staging environment in London
What
----
A new Architecture Decision Record to document the decision to run a single staging environment in the London region.
How to review
-------------
```
bundle exec middleman build
bundle exec middleman server
```
Review content in the context of the team manual website for accuracy and completeness
Who can review
--------------
- Alex
- Henry
> initial draft of ADR030

- source/support/support_manual.html.md
What
----
Urmi's gone to GOV.UK, so she probably doesn't want to be adding people
to Zendesk anymore.
How to review
-------------
Quick sanity check should be fine
Who can review
--------------
Anyone
> s/Urmi/the PaaS delivery manager/

- source/guides/trial_accounts.html.md
What
----
This makes it easier to generate CSV files to upload to Notify for notifying tenants.
How to review
-------------
Review as part of https://www.pivotaltracker.com/n/projects/1275640/stories/160340542
Who can review
--------------
Anyone but me.
> [#160340542] Update trial accounts guidance

- source/team/notifying_tenants.html.md
What
----
The folder has been moved to the team drive.
How to review
-------------
Just check the link is correct and merge. No faffing around.
Who can review
--------------
Anyone but me.
> [#160508378] Update link to Google Drive

- source/guides/vpc_peering.html.md
- source/index.html.md
What
----
These have been moved from paas-cf
How to review
-------------
Review with https://github.com/alphagov/paas-cf/pull/1619
Who can review
--------------
Anyone but me.
> [support] Add VPC peering docs

- source/accounts/billing_info.html.md
- source/index.html.md
What
----
This PR adds the billing process information into the team manual.
How to review
-------------
Run it locally and check the contents against the story
Who can review
--------------
Anyone
> [#162199166] Add billing info to team manual

- source/guides/Tenant_Application_Penetration_Testing.html.md
What
----
The script we were using to list the RDS instances for a pen testing
was wrong and was not listing the guid of the service_isntance,
but the unique_id of the service offering (e.g. psql small).
The right way to do it would be:
1. Query the guid of the service offering for the rds_broker.
2. List the service_instances in the org with that guid in service_guid.
We update the script to support this.
How to review
-------------
Code review. Test the script with a random org.
Who can review
--------------
not me
> [#SUPPORT] Fix how to get RDS instances for a given org

- source/support/finding_activity.html.md
Title says it all.
Read + local preview
Not me.
> [#161420552] Add useful Kibana filters to find internal application logs

- source/javascripts/application.js
What
----
Originally this was using Hector's account, but he's left now so the
integration has broken.
I've created a new integration and invited all the civil servants on the
team to be administrators.
I did this:
* Go to https://cse.google.co.uk/cse
* Click add
* Fill in details of https://team-manual.cloud.service.gov.uk/
* Copy the `cx` code out of the snippet it gives you and update it in
`source/javascripts/application.js
* Add all the people on the team in the admins tab
Hopefully we shouldn't have to do this again because we've got several
people administering it now.
How to review
-------------
* Code review
Who can review
--------------
> Update google search to use richardtowers' account

- source/index.html.md
- source/support/support_manual.html.md
- source/team/service_targets.html.md
What
----
Added the service targets to the Team Manual
How to review
-------------
Ensure that they match up to the targets stated in the ticket, and if they are in a logical place
Who can review
--------------
Not Me
> [#163229372] Add Service Targets to Team Manual

- source/team/orientation.html.md
What
----
... so we don't forget to do it again...
How to review
-------------
* Check that I haven't lied or said anything offensive or horrible.
Who can review
--------------
* Not @richardtowers
> Add a short paragraph on buddying

- source/accounts/billing_info.html.md
What
----
Updated the documented billing process so it matched recent changes.
How to review
-------------
Code review - changes have already been 2-eyed by @jonathanglassman
Who can review
--------------
Not @tnwhitwell
> [#164046968] Update billing process

- source/guides/Tenant_Application_Penetration_Testing.html.md
What
----
Since AWS have changed their approvals process on penetration and load testing we need to reflect this information in the team manual. It is still of value for us to know that tests are occurring and to have suitable information to contact the testers if issues arise.
How to review
-------------
Code review and run locally
Who can review
--------------
Not @LeePorte
> Update information regarding penetration and load testing

- source/index.html.md
- source/support/finding_noisy_apps.html.md
What
----
We have enabled the noisy neighbour nozzle, this commit adds a page about what it is and how to use the nozzle.
How to review
-------------
Run it locally and make sure it makes sense
Who can review
--------------
anyone
> [#161684547] Add nosy neighbour info to manual

- source/support/support_manual.html.md
What
----
1) Correct the links to Grafana
2) Add a handy link to the build Concourse
How to review
-------------
1. Code review
2. Check the links work and go where they should
Who can review
--------------
Anyone
> Improve support manual's useful links

- source/guides/restoring_bosh_director.html.md
- source/index.html.md
What
----
...and recovering from a missing DB.
How to review
-------------
Copy review
Who can review
--------------
Anyone
> [#164964236] Document bringing up a Bosh director in another AZ

- source/architecture_decision_records/ADR031-services-core-pipeline-separate-jobs.html.md
What
----
Add an ADR for changes to the pipeline
How to review
-------------
Agree with the ADR
Who can review
--------------
Not @tlwr
> ADR 31 - separate jobs in cloudfoundry pipeline

- source/accounts/getting_data_about_trial_accounts.html.md
What
----
Update process on how to get org data
How to review
-------------
Docs review
Who can review
--------------
Someone who has done a `another month` story
See other
---
https://github.com/alphagov/paas-cf/pull/1882
> [#165738903] Update process for getting org data

- source/support/zendesk.html.md
What
----
We're going to use these from now on to categorize support tickets.
How to review
-------------
* Check you agree with where to document this
* Probably not worth spending too much time checking the tags, because
they've already been reviewed, but comments welcome.
Who can review
--------------
Not Rich or Jake
> Document our zendesk tags

- source/support/zendesk.html.md
What
----
Describe what you have changed and why.
How to review
-------------
Describe the steps required to test the changes.
Who can review
--------------
> fix typo - mointering becomes monitoring

- source/guides/effective_remote_pairing.html.md
- source/index.html.md
What
----
I wrote up some guidance for using the remote pairing tools effectively, based on my experiences using them.
How to review
-------------
1. Copy review
2. Make suggestions if you have any
Who can review
--------------
Anyone
> Add guidance for effective remote pairing

- source/guides/releasing_bosh_blobs.html.md
What
----
As we are now using assume role, the previous guidance was a little outdataed.
This now takes account of both the changes that are needed to be made to `config/private.yml` and to the command to upload the bosh blobs.
How to review
-------------
Read it and check it makes sense, feel free to try it out on a boshrelease.
Who can review
--------------
Anyone
> Update bosh release guidance

- source/architecture_decision_records/ADR445-continuously-deploy-platform-cf-apps.html.md
What
----
Add an ADR to record the decision to change the way the CF apps
(paas-admin, paas-billing and paas-cf) are deployed by the pipeline.
How to review
-------------
* Check the ADR is correct and understandable
Who can review
--------------
Not Rich
> Record the decision to continuously deploy CF apps

- source/index.html.md
What
----
Forgot to do this in the last pr 🤦‍♂
How to review
-------------
* code review is enough
Who can review
--------------
Not @richardTowers
> Add link to ADR445 (continuously deploy apps)

- source/architecture_decision_records/ADR446-do-not-use-haproxy-use-aws-alb.html.md
What
----
Add ADR for HAProxy and ALB work
How to review
-------------
Paired with @richardTowers
> ADR446: HAProxy ; AWS ALB

- source/accounts/billing_info.html.md
What
----
Wrote the google doc into markdown
How to review
-------------
Done as pair with Emma
> Update billing documentation with Emma's 🧠

- source/team/orientation.html.md
The author is _Julia_ Evans, at least according to https://jvns.ca/about/ and https://twitter.com/b0rk
> Correct author’s name in link to blog post

- source/architecture_decision_records/ADR447-add-new-rds-broker-plans.html.md
- source/index.html.md
What
----
Adds an architectural decision record to create some new database plans.
How to review
-------------
* Review the ADR
* Once approved, send it back to @richardtowers to raise the follow up
stories and update the ADR with links.
Who can review
--------------
> Add ADR447 - new RDS broker plans

- source/guides/Github_oAuth_in-Dev.html.md
What
----
We're making Github auth the default in dev, so there was a small tweak required to the command used when pushing pipelines.
How to review
-------------
Code review
Who can review
--------------
Anyone
> Update github auth info

- source/incident_management/incident_process.html.md.erb
What
----
The current link points to a completed incident report. I have updated this to point to a blank incident report template.
How to review
-------------
Check that the link now points to the template doc
Who can review
--------------
anyone
> Update incident report template link

- source/architecture_decision_records/ADR448-automated-certificate-rotation.html.md
- source/guides/upgrading_CF,_bosh_and_stemcells.html.md
- source/incident_management/responding_to_alerts.html.md
- source/index.html.md
- source/team/rotating_credentials.html.md
What
----
Adds ADR448 about automated certificate rotation
How to review
-------------
1. Copy review
2. Check it all renders OK
Who can review
--------------
@mogds to check for correctness, and one other person for clarity.
> [#166282717] Add ADR448 about automated certificate rotation

- source/architecture_decision_records/ADR449-audit-logs-in-splunk.html.md
- source/index.html.md
[Story](https://www.pivotaltracker.com/story/show/169258551)
What
----
This ADR documents work that has already been done
How to review
-------------
Read the words
Review [the stories in the epic](https://www.pivotaltracker.com/n/projects/1275640/stories/169258551/expand)
Who can review
--------------
Not @tlwr
> [#169258551] Add ADR for storing and shipping audit events

- source/team/orientation.html.md
What
----
As we have moved standup time to be inside core hours this should b e reflected in the team manual.
How to review
-------------
Code review
Who can review
--------------
Anyone
> Update standup time

- source/accounts/billing_info.html.md
What
----
Add a paragraph documenting how we set the GBP/USD exchange rate.
How to review
-------------
* Check this makes sense / confirm that this process is in place
Who can review
--------------
Best for Luke to have a look before merging.
> WIP: Document how we set the exchange rate

- source/guides/effective_remote_pairing.html.md
What
----
Fixed a typo
How to review
-------------
Check the typo is fixed
Who can review
--------------
> Fix typo `s/floorignore/flooignore/`

- source/team/managing_access_to_cloud_services.html.md
What
----
Document the new operator role, how it differs from the Admin role, and
when to use which role.
How to review
-------------
* Check the docs make sense
* No need for tech writer 2i, as this is internal documentation
Who can review
--------------
> Document the Operator and Admin roles

- source/guides/cf_admin_users.html.md
[Story](https://www.pivotaltracker.com/n/projects/1275640/stories/170702697)
What
----
Document the changes that we have made in the story, to how we access production
How to review
-------------
👀 
Who can review
--------------
Not @tlwr
> [#170702697] Document two levels of production access

- source/architecture_decision_records/ADR451-bosh-access-without-socks.html.md
- source/architecture_decision_records/ADR452-bosh-access-with-mtls.html.md
- source/architecture_decision_records/images/adr451-bosh-access-without-socks.svg
- source/architecture_decision_records/images/adr452-bosh-access-with-mtls.svg
- source/index.html.md
What
----
This commit adds the new ADR taken on how to move forwards with removing the final shared credentials in use as part of PCI compliance and better securing the platform.
How to review
-------------
Spin it up locally and check that everything renders correctly.
Read the ADR and check it makes sense.
Who can review
--------------
Anyone
> [#170894236] Add ADR 451

- source/architecture_decision_records/ADR453-isolation-segments.html.md
- source/index.html.md
What
----
Add ADR 453 on isolation segments
The private document has been reviewed and is now ready for being added to our public team manual, pending clarifications and suggestions by the wider team
_Rendered view_
How to review
-------------
👀 and 🤔 
Who can review
--------------
Not @tlwr
Consider the :goat:
> Add ADR 453 on isolation segments

- source/guides/Connecting_to_Concourse_CredHub_and_BOSH.html.md
- source/guides/Connecting_to_Concourse_and_BOSH.html.md
- source/guides/IPSec_debugging.html.md
- source/index.html.md
What
----
Update our documentation not to mention shared creds
Update our documentation to include CredHub
How to review
-------------
Read the words 🤓 
Who can review
--------------
Not @tlwr
> Sso cli bosh

- source/accounts/account_lifecycle.html.md
- source/support/CF_UAA_user_management.html.md
What
----
Pointing to the new pazmin feature.
How to review
-------------
- Sanity check
> Encourage to use pazmin's new feature

- source/team/rotating_credentials.html.md
What
----
The documentation on how to rotate platform credentials had not been substantially updated since it was written in #98 in 2017. In that time we've moved to Credhub and done various other things.
This commit refreshes the documentation, tries to improve clarity, and adds sensible warnings and context.
The strongest motivation for this change (other than doing #341 to this page at the same time) was that _"First, you delete credentials using one of the CI helper jobs."_ is _wrong_ now. We never delete credentials from Credhub, we regenerate them.
How to review
-------------
Compare the old and new documentation. Do you think the new form is clearer? Give feedback.
Who can review
--------------
Not @46bit.
> Refresh how to rotate the platform credentials

- source/incident_management/incident_process.html.md.erb
- source/team/notifying_tenants.html.md
What
----
Updated the support process for in and out of hours on call engineers and comms leads.
How to review
-------------
Spin it up locally and read changes to make sure they make sense.
Who can review
--------------
Anyone.
> Update support process

- source/index.html.md
- source/team/comms_lead_role.html.md
What
----
These are some notes taken during the comms lead training session and are
here as a quick reference for when you forget what you're doing at 3 am.
How to review
-------------
Run it locally and check that the links work and the words make sense
Who can review
--------------
Anyone
> Added comms lead role notes

- source/support/zendesk.html.md
What
----
We get quite a lot of tickets about logs (relative to others), but we've never had a single tag to add. This introduces one.
How to review
-------------
1. Copy review
2. Do you even agree with it?
Who can review
--------------
Anyone! It's a free for all!
> Add a logs category to the ZenDesk ticket tags

- source/accounts/account_lifecycle.html.md
Document for tracking adoption has changed. Updated link for PMs to find.
What
----
Changed the link to the new adoption tracker.
How to review
-------------
Check the link.
Who can review
--------------
Not Mark Buckley.
> Update list of live services link

- source/index.html.md
- source/support/viewing_our_data_in_splunk.html.md
What
----
I always forget the starting point is to search for `index="paas"`, and it is surprisingly hard to find the data without knowing that. I've added that to the team manual so I can stop asking Cyber every time.
How to review
-------------
Read it and OK it. :)
Who can review
--------------
Not @46bit.
> Make a note of how to see our data in Splunk

- source/index.html.md
- source/team/roadmap.html.md
What
----
Document the roadmap and how we use it
How to review
-------------
Copy review
Who can review
--------------
Anyone
> Document the roadmap and how we use it

- source/index.html.md
What
----
Correct link to the roadmap documentation
How to review
-------------
It's a 1 char change.
Who can review
--------------
Me
> Correct link to the roadmap documentation

- source/support/CF_UAA_user_management.html.md
What
----
Split up a long block of text for accessibility reasons and reworded the content a bit to make it clearer
How to review
-------------
1. Preview locally to check that the content looks OK.
2. Check that the content is still accurate from a technical perspective.
Who can review
--------------
Someone who knows about how to lock CF user accounts
> Split up block of text and make content clearer

- source/accounts/getting_data_about_trial_accounts.html.md
- source/architecture_decision_records/ADR008-haproxy-for-request-rewriting.html.md
- source/architecture_decision_records/ADR040-bosh-access-without-socks.html.md
- source/architecture_decision_records/ADR043-new-product-pages-language-and-framework.html.md
- source/guides/editing_logstash_filters.html.md
- source/guides/effective_remote_pairing.html.md
- source/guides/vpc_peering.html.md
- source/incident_management/roles_and_responsibilities.html.md
- source/incident_management/support_manual.html.md
- source/support/CF_UAA_user_management.html.md
- source/team/comms_lead_role.html.md
- source/team/notifying_tenants.html.md
- source/team/pagerduty.html.md
What
----
Found multiple instances of non-accessible language (for example, 'click', 'simply') and removed or replaced them where possible
How to review
-------------
Preview locally and check that the content looks OK
Who can review
--------------
Anyone but @cmcnallygds
> Remove language which is not accessible

- source/accounts/account_lifecycle.html.md
- source/accounts/getting_data_about_trial_accounts.html.md
- source/architecture_decision_records/ADR009-x-forwarded-headers.html.md
- source/architecture_decision_records/ADR015-rds-storage-encryption-plans.html.md
- source/architecture_decision_records/ADR032-ssl-only-for-applications-and-cf-endpoints.html.md
- source/architecture_decision_records/ADR037-automated-certificate-rotation.html.md
- source/architecture_decision_records/ADR039-aiven-metrics-for-users.html.md
- source/guides/IPSec_debugging.html.md
- source/guides/effective_remote_pairing.html.md
- source/guides/restoring_bosh_director.html.md
- source/guides/spruce.html.md
- source/incident_management/incident_process.html.md.erb
- source/incident_management/support_manual.html.md
- source/team/notifying_tenants.html.md
- source/team/pagerduty.html.md
- source/team/service_targets.html.md
What
----
Removed instances of bold and italic text used for emphasis, as it is hard to read and not accessible
How to review
-------------
Preview locally and make sure it all looks good
Who can review
--------------
Anyone but @cmcnallygds
> Remove use of bold and italic text for accessibility

- source/team/dashboard_mac_mini.html.md
What
----
Fixed broken links and link text
How to review
-------------
Preview content locally and check that links work
Who can review
--------------
@tlwr
> Fix broken links and bad link text

- source/architecture_decision_records/ADR040-bosh-access-without-socks.html.md
- source/architecture_decision_records/ADR041-bosh-access-with-mtls.html.md
- source/guides/vpc_peering.html.md
- source/team/working_practices.html.md
What
----
Removed references to IP white lists as per accessibility guidance
How to review
-------------
Preview locally and make sure content looks OK
Who can review
--------------
Anyone
> Remove references to white lists

- source/team/working_practices.html.md
What
----
Changed wording of some links to make them more descriptive
How to review
-------------
Check the links still make sense and still work
Who can review
--------------
Anyone but @cmcnallygds
> Fix link text for accessibility

- source/index.html.md
What
----
Fixed broken link to archived GDS styleguides
How to review
-------------
Check that the link works now
Who can review
--------------
Anyone
> fix link to styleguides

- source/support/shipping_elasticsearch_metrics_to_tenants.html.md
What
----
The diagram was not previously explained in full in the text on this page. This change aims to explain its content in full for users who cannot see the diagram.
How to review
-------------
Preview the content locally and check that it is accurate
Who can review
--------------
Not @schmie or @cmcnallygds
> Add explanation of diagram for accessibility

- source/architecture_decision_records/ADR044-remove-ipsec.html.md
> Re-add-adr044 to fix failing build

- source/team/working_practices.html.md
What
----
Updated the steps in the development process to create a numbered list and clearer, more specific points.
How to review
-------------
Check that the content is accurate and free of mistakes/typos.
Who can review
--------------
not @cmcnallygds
> Update steps in development process

- source/accounts/closing_trial_accounts.html.md
What
----
Add command for how to suspend an org. This is a `cf curl` command so is not obvious and we don't have it
documented anywhere.
How to review
-------------
Code review
Who can review
--------------
Anyone
> Add command for how to suspend an org

- source/accessibility.html.md.erb
- source/monitoring_alerting/audit.html.md
What
----
I've reworded some of this guidance to make it clearer and more concise
How to review
-------------
1. Preview the content locally
2. Check that it still makes sense from a technical perspective
Who can review
--------------
not @cmcnallygds
> Make guidance clearer and more concise

- source/architecture_decision_records/ADR040-bosh-access-without-socks.html.md
What
----
Have made some style improvements for clarity and better accessibility.
How to review
-------------
1. Preview locally and make sure it renders correctly.
2. Check that the content is still accurate and up-to-date.
3. Check that the content accurately represents the information given in the diagram. If anything is missing or incomplete, please suggest an improvement.
Who can review
--------------
Not @cmcnallygds
> Make style improvements 

- source/accessibility.html.md.erb
What
----
Removed links to the two pages we have recently fixed
How to review
-------------
Preview locally and make sure the content renders correctly
Who can review
--------------
Not @cmcnallygds
> Remove links to fixed pages

- source/architecture_decision_records/ADR039-aiven-metrics-for-users.html.md
What
----
Have made some improvements so that the content is in line with the style guide and is easier to read.
How to review
-------------
1. Preview the content locally.
2. Make sure the changes have not altered the meaning of the content from a technical perspective.
3. Make sure the content accurately reflects what the diagram shows. If it does not, please suggest an improvement.
Who can review
--------------
Not @cmcnallygds
> Improve style and clarity for accessibility

- source/architecture_decision_records/ADR041-bosh-access-with-mtls.html.md
- source/architecture_decision_records/images/adr452-bosh-access-with-mtls.svg
What
----
Have made some improvements so that the content is in line with the style guide and is easier to read. 
How to review
-------------
1. Preview the content locally.
2. Make sure the changes have not altered the meaning of the content from a technical perspective.
3. Make sure the content accurately reflects what the diagram shows. If it does not, please suggest an improvement.
Who can review
--------------
Not @cmcnallygds
> Make style improvements

- source/architecture_decision_records/ADR039-aiven-metrics-for-users.html.md
What
----
Include all components depicted in the diagram of the Aiven metrics for
users ADR in the accompanying text to improve accessibility.
How to review
-------------
Review changes in a local instance of the manual.
Who can review
--------------
@cmcnallygds
> Update text to match diagram in ADR039

- source/guides/looking_up_users_by_google_id.html.md
What
----
Fix missing h1 to have a successful build
> Fix missing h1

- source/guides/common_support_tasks.html.md
What
----
Moved some relevant lines over from https://docs.google.com/document/d/14ulAP1DbuK_NmNE2mZTVRZkg3wTw2deduZD74xGMjSc/edit?ts=5b7e7c6f#
Looks like this in the UI:
How to review
-------------
Look good? In the right place?
Who can review
--------------
Would love to hear from content people, as well as people who will use this runbook
> WIP: Add exemplar support tasks

- source/guides/reducing_logit_volume.html.md
- source/index.html.md
What
----
Add instructions for reducing Logit volume.
paas-cf reference will only be valid after https://github.com/alphagov/paas-cf/pull/2695
How to review
-------------
Doc review.
Who can review
--------------
Not @Krenair
> Add instructions for reducing Logit volume

- source/architecture_decision_records/ADR046-postgres-plans.md
- source/index.html.md
What
----
Add ADR046: Postgres plans
How to review
-------------
Read it and decide whether I missed anything, made any bad suggestions, made any errors, etc.
Who can review
--------------
Not @Krenair
> Add ADR046: Postgres plans

- source/guides/finding_useful_links.html.md
What
----
Add info to find useful paas links with `gds-cli`
How to review
-------------
I guess just read it?
Who can review
--------------
Not @me
> Add info for finding paas links with `gds-cli`

- source/guides/resolving_Kibana_indexing_errors.html.md
- source/index.html.md
What
----
Add guidance on resolving Kibana indexing errors.
Following a cf-deployment we were required to refresh the logstash field list in order to be able to query Kibana.
How to review
-------------
- Code review / check locally.
Who can review
--------------
not @schmie
> Add guidance on resolving Kibana indexing errors

- source/architecture_decision_records/ADR0048_add_resources_table.md
- source/architecture_decision_records/ADR0049_calculate_bills.md
What
----
Added 2 ADR for new billing redesign
How to review
-------------
No tests required
Who can review
--------------
Not @poveyd
> Record of design decisions made for new GOV.UK PaaS billing

- source/team/orientation.html.md
What
----
Update team page with leavers and joiners
How to review
-------------
run locally
> Update team page

- source/guides/common_support_tasks.html.md
- source/guides/resolving_Kibana_indexing_errors.html.md
- source/incident_management/incident_process.html.md.erb
- source/index.html.md
- source/support/restoring_opensearch_backups.html.md
- source/support/shipping_elasticsearch_metrics_to_tenants.html.md
- source/support/zendesk.html.md
- source/team/managing_access_to_cloud_services.html.md
What
----
Replaces elasticsearch references with opensearch where appropriate 
How to review
-------------
Code review
Who can review
--------------
Not me
> [#181627481] Replace elasticsearch references with opensearch

- source/guides/upgrading_CF,_bosh_and_stemcells.html.md
What
----
Our buildpack upgrade guide was a little out of date, and didn't mention the Make target or the differing responsibilites of reviewer and developer.
How to review
-------------
1. Copy review
2. Does it makes sense and match what we do?
> Mention the Make target for buildpack upgrades

- source/team/rotating_credentials.html.md
What
----
Generally improves the rotating credentials documentation, with a specific focus on rotating BOSH certs
How to review
-------------
Am I wrong? Did I miss anything?
> Improve docs on rotating BOSH certs

- .github/workflows/pr-tests.yml
What
----
Add git to the container due to 
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
How to review
-------------
Code review
Who can review
--------------
Anyone
> Add git to the deploy container

- .github/workflows/deploy.yml
What
----
Add git onto the right workflow, because I edited the wrong file.
How to review
-------------
Describe the steps required to test the changes.
Who can review
--------------
> Add git onto the right workflow

- .github/workflows/deploy.yml
What
----
Add write permissions for the deploy workflow
How to review
-------------
Code review
Who can review
--------------
@kr8n3r
> Add permissions

- source/guides/manage_frontend_dependencies.html.md
- source/index.html.md
What
----
Add notes on where and how to manage frontend dependencies
How to review
-------------
[Rendered file](https://github.com/alphagov/paas-team-manual/blob/efd097672f258bd869af6e3f09eaaf8443bd6b9b/source/guides/manage_frontend_dependencies.html.md)
Who can review
--------------
anyone
> Document managing frontend dependencies

- source/incident_management/incident_process.html.md.erb
What
----
:point_up: 
As a result of https://www.pivotaltracker.com/story/show/182400204
How to review
-------------
:eyes:
> incident process: update information about responsibility for Big Concourse

- source/accounts/account_lifecycle.html.md
- source/accounts/closing_trial_accounts.html.md
What
----
Part of https://www.pivotaltracker.com/story/show/181359504
Add deprecation notice to trial account request steps
Add deprecation notice to closure of trial accounts
How to review
-------------
review text
Who can review
--------------
not @kr8n3r
> Deprecation notice to trial account processes

- source/team/orientation.html.md
What
----
Adds our new joiners to the team member names, and alphabetises the list.
How to review
-------------
Did I miss anyone? (Sorry!)
> Update team member names and alphabetise them

- source/accounts/close_billable_accounts.html.md
- source/index.html.md
What
----
Document billable account closure process
[View rendered](https://github.com/alphagov/paas-team-manual/blob/e4030e7db3a4f06e762d3745ebd7676fc9585f33/source/accounts/close_billable_accounts.html.md)
Who can review
--------------
anyone
> Document billable account closure process

- source/accounts/close_billable_accounts.html.md
Signpost to script for suspending accounts in paas-cf
script was added in alphagov/paas-cf#3073, so this will need to be merged first for this change to be correct
👀
Not me
> Close billable accounts: Signpost to suspension script in paas-cf

- source/incident_management/roles_and_responsibilities.html.md
Update link to reflect new incident management guidance content
What
----
Fix link to incident management guidance
How to review
-------------
Check that content displays and is accurate
Who can review
--------------
@AP-Hunt
> Fix link to incident management guidance

- source/accounts/close_billable_accounts.html.md
What
----
Update the step about where and what to record about closures
How to review
-------------
- run locally or just review changes
Who can review
--------------
not @kr8n3r
> Update step about recording closure

- source/guides/upgrade_concourse.html.md
- source/index.html.md
Description:
- Adds a team manual page outlining how to upgrade Concourse
- With @cmcnallygds
> 184571249 - Document Concourse upgrade

- source/guides/upgrade_concourse.html.md
What
----
Update concourse upgrade document afters locking concourse image to fixed version
How to review
-------------
Check the changes.
Who can review
--------------
Any team member
> Update concourse upgrade document

- source/support/so_you_are_on_support.html.md
- source/team/working_practices.html.md
What
----
Since we last touched this area, we've changed exactly how we make signed merges and how we manage GPG keys.
How to review
-------------
Is what I wrote correct?
Does it look alright in the browser?
> [#184950449] Bring merge signing and GPG guidance up to date

- .github/dependabot.yml
Description:
- Configures Dependabot to raise PRs for GitHub actions weekly
How to review
-------------
Code review
Who can review
--------------
Anyone but me
> 185509385 - Configure Dependabot for GitHub actions

- .github/workflows/deploy.yml
Description:
-------------
- Following from the [GitHub pages pipeline for paas-tech-docs](https://github.com/alphagov/paas-tech-docs/pull/512) this refactors the pipeline to deploy using artifacts rather than branches
How to review
-------------
Code review.
> 185550872-Refactor-GitHub-pages-pipeline

- .github/workflows/deploy.yml
Reverts alphagov/paas-team-manual#499
> Revert "185550872-Refactor-GitHub-pages-pipeline"

- .github/workflows/deploy.yml
Description:
----
- Following from the [GitHub pages pipeline for paas-tech-docs](alphagov/paas-tech-docs#512) this refactors the pipeline to deploy using artifacts rather than branches
How to review
-------------
Code review
> 185550872 - Refactor GitHub pages pipeline

- README.md
Description:
----
- Updates README to reflect that we deploy to GitHub pages
How to review
-------------
Code review.
> 185550872 - Update README

- README.md
Description:
----
- Add the right markdown syntax to fix the broken link
> BAU - Fix broken link

- source/accounts/close_billable_accounts.html.md
- add reference to new script to delete users
What
----
Describe what you have changed and why.
How to review
-------------
Describe the steps required to test the changes.
Who can review
--------------
> improved closure guidance

- source/architecture_decision_records/ADR053-paas-product-pages-ireland.html.md
- source/index.html.md
Description:
----
- Draft ADR on maintaining paas product pages post ireland
Who can review
--------------
PaaS Team
> 185986921 - Draft ADR for maintaing paas product pages post ireland

- source/accounts/close_billable_accounts.html.md
What
----
Added a step to check the current org status with a script
How to review
-------------
👀 
Who can review
--------------
Any SRE
> Add a step to check the current org status

- source/guides/updating_docker_images.html.md
- source/index.html.md
What
----
added docker update howto
How to review
-------------
Run the local preview and look the the changes
Who can review
--------------
Any paas dev
> added docker update howto

- source/accounts/close_billable_accounts.html.md
What
----
Decommissioning org users is the last step of the sequence of steps we do before updating the spreadsheet.
How to review
-------------
Verify that the order of things is true.
Who can review
--------------
PAAS team members
> Decommisioning task reflect order

- source/index.html.md
- source/upcoming_plans/decommissioning_central_paas_infrastructure.html.md
What
----
Add steps for decommissioning central PaaS infrastructure.
How to review
-------------
Check out the branch, run `bundle exec middleman server` (after `bundle install`ing the dependencies) and browse the generated site locally using the URL given in the console output
> Add page about decommissioning central PaaS infrastructure
