README.md

I set this up by:
1. Signing up for an RTD account.
2. Manually creating a new project (I didn't want to grant it access to my
GitHub account).
3. Giving it the public URL of this GitHub repo.
4. Changing the "documentation type" from Sphinx to MkDocs.
5. Disabling PDF and ePub builds, because I don't expect us to need them and
it will speed up the build process slightly.
6. Adding @alextomlins and @timothymower as "maintainers" who have admin
access to the settings.
7. Enable the service integration on the GitHub repo (it doesn't take any
settings, just on/off).

[#108440080] Link to built/hosted site on Read the Docs

---

docs/guides/GPG.md

Not everybody will have used GPG before, or recently. This guide is intended
to make it easier for people, including but not limited to new starters, to
setup their machines. We can link to it from other repos like
government-paas/credentials so that we don't have duplication.
It also gives us a bit of structure to the team manual. This doesn't
strictly fit under the "team" section. I expect that we'll have other short
guides like this in the future and maybe a top-level for Cloud Foundry
specific information.
I've mostly paraphrased these instructions from:
- https://github.com/alphagov/tsuru-ansible#setting-up-gpg-encrypted-vault-password-support
With the following changes:
- use long fingerprints instead of short fingerprints
- collapsed the installs into single commands
- omit the …

[#108440080] Add guides/GPG

---

docs/team/orientation.md

**What**
We want to add dockerhub to the list of services we use
**How this PR should be reviewed**
This PR should reviewed in the following context:
* I want dockerhub to be on the list of services in the orientation page
**How to test this PR**
Follow the instructions  in the Readme to locally build this branch, then browse to http://127.0.0.1:8000/team/orientation/ and check that dockerhub appears.
**Who should review this PR**
* Anyone but me

[##109029950 Add dockerhub to list of used services]

---

docs/team/orientation.md

To match the other URLs and help people locate the things that we own.

[#109029950] Add organisation to Docker Hub URL

---

docs/guides/CloudFoundry_debugging.md

This documents how to download a remote CF container that has
successfully staged but does not run correctly, allowing you to inspect
the contents and figure out why a user-uploaded app is not functioning.

Start of useful documentation on debugging CF

---

docs/guides/spruce.md

I was reading the spruce guide and noticed that the referenced PR was merged and released into spruce v0.13.0, so I updated the instructions to use go get to fetch the source instead of git.
I assumed we had no other reason to build from source.
I've tested that the OR operator example works after following the new installation steps.

Update spruce guide now operand expressions PR is merged

---

docs/arch/adr-001-manifest-management.md

This is an idea that comes from [this blog
post](http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions)
It is useful to keep a record of decisions that have been made on the
project, and this seems like a reasonable format for it.
A [good example of this on another
project](https://github.com/openregister/presentation/blob/95ffd16deacd4ee2f4161f2d3af53805fa708fbe/doc/arch/adr-001-remove-kafka.md)

[#108528644] Architecture decision record - manifest management

---

docs/team/responding_to_aws_alert.md

So that team members have some idea of when to look at the process document.
This description has been copied from the first paragraph of the doc.

[#109787160] Describe the types of AWS alerts

---

docs/team/working_practices.md

Document how we sign off stories.
Some new team members recently started. The team has been experiencing contention signing stories off, with the WIP limit on the awaiting sign-off column (currently set to 3) being reached several times.
Most of the people involved in sign off  (product managers, delivery manager, tech lead, tech arch, analyst, senior developer) met and agreed what, if anything we wanted to change.
@dcarley @brettansley @alext and anyone else who was part of that discussion
Ensure this matches your recollection of what we agreed.

Document who can and how we sign off stories

---

docs/team/orientation.md

With links to blogs and videos that explain why we're here and what we've
been doing so far. We can add Rory's next blog post(s) to this as they are
published.

Add product section to orientation page

---

docs/team/working_practices.md

- link to out pull request template in alphagov/paas-cf instead of
duplicating here
- use bullet points for the things you need to do when creating a pull
request
I've omitted the part about not putting story numbers on individual commits
because it came from a previous team in GDS where we did that and I don't
expect anyone new to this team would do that by default.
This came from a team discussion a few weeks ago. Possibly a retrospective.

Refactor and extend PR guidance

---

docs/team/working_practices.md

In our retrospective of 8/3/2016 we discussed some occasions when two stories
played at the same time changed the same lines of code in different ways. This
caused a number of merge conflicts that needed to be resolved before finished
stories could be merged into master.
We agreed that the best way to avoid difficult and time consuming merges was to
identify at kick-off time if was likely that the story being kicked off would
cause conflicts with a story already in play.

Retro action: check for conflicting work at kickoff

---

docs/team/working_practices.md

To specify write access.
This has caught me out a couple of times because the default in the
github ui is to give read access only, hopefully specifying this in the
manual should help

Update adding contractors to git instructions

---

docs/architecture_decision_records/ADR008-haproxy-for-request-rewriting.md

[#115931361 Ensure correct HSTS headers are being served](https://www.pivotaltracker.com/story/show/115931361)
What
---
We want to serve [HSTS
headers](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) for all
HTTPS requests to the apps domains, but it will safeguard existing users from
being MITMed over insecure connections and it will improve the user experience
when they click on a hostname that doesn't have a protocol.
(Note that without pre-loading in browsers this won't help first time users,
but that is out of context)
In this PR we add ADR explaining the context and decision of setting up HAProxy
in front of the gorouters.
Who?
---
Anyone but @keymon or @HenryTK

[#115931361] Add ADR for HAProxy in front of gorouter

---

README.md

I received an email from Read The Docs that says:
> Starting today, Read the Docs will start hosting projects from subdomains
> on the domain readthedocs.io, instead of on readthedocs.org. This change
> addresses some security concerns around site cookies while hosting user
> generated data on the same domain as our dashboard.
They do serve a redirect from the old to new domain, however they will
deprecate it one day and per rtfd/readthedocs.org#2175 the protocol isn't
preserved. So it's best that we update our links.
When merged I'll also update the URL in the repo description.

Update readthedocs domain

---

docs/architecture_decision_records/ADR009-x-forwarded-headers.md

This PR describes the decision to disable SSL between ELB and HAProxy.
As we want to use ProxyProtocol between ELB and HAProxy and the
implementation, when SSL is enabled, is not compatible we need to
disable SSL.
Do proof reading and check if it makes seanse
not @combor or @keymon

Decision to disable SSL between ELB and HAProxy

---

docs/team/working_practices.md

We agreed these conditions in a retrospective because we found that people
were reluctant to change pairs. The 2 day rule ensures that people don't get
stuck on large stories and that we fresh ideas on existing problems. The
joining people ensures that people don't remain without a pair or wait until
standup for rotation.
Read the new text and see if it makes sense. You can preview the rendering of the bullet points by following the instructions in the README.
Not @dcarley

[#121502387] Update conditions for rotating pairs

---

docs/architecture_decision_records/ADR008-haproxy-for-request-rewriting.md
docs/architecture_decision_records/ADR012-haproxy-healthcheck.md

Explain why we have a port 82 healthcheck port on HAProxy
We previously documented why we introduced HAProxy in front of the gorouter, so it's useful to capture our new reason for having HAProxy in place. 
I aksed the team and @keymon also thought this would be useful
Read the words what I wrote and decide if they are accurate and understandable
Anyone but @bleach

[#121933113] - Document HAProxy healthcheck port on routers

---

docs/architecture_decision_records/ADR011-security-group-structure.md

This adds an ADR for the decision about how we will structure security groups.
As a note, there is one point where this deviates from what was discussed in the meeting: we discussed having separate ingress and egress groups for components that both provide services, and consume other services. This was to avoid cycles in the Terraform graph. We've instead proposed avoiding this by using the [`aws_security_group_rule` Terraform resource](https://www.terraform.io/docs/providers/aws/r/security_group_rule.html) instead of defining the rules inline.
Read. Confirm this makes sense, and is something we want to adopt.
Anyone but @HenryTK or myself.

Add ADR for security groups pattern.

---

docs/architecture_decision_records/ADR003-AWS-credentials.md

To cover work across the following stories:
IAM roles and profiles:
- https://www.pivotaltracker.com/story/show/109806354
- https://www.pivotaltracker.com/story/show/110246622
- https://www.pivotaltracker.com/story/show/111138770
- https://www.pivotaltracker.com/story/show/110238314
- https://www.pivotaltracker.com/story/show/110311736
- https://www.pivotaltracker.com/story/show/111303414
- https://www.pivotaltracker.com/story/show/111778374
- https://www.pivotaltracker.com/story/show/111523754
IP restrictions:
- https://www.pivotaltracker.com/story/show/109625018
This topic has come up in a few conversations recently because we've been
experiencing problems with the EC2 instance metadata service. So it would be
useful to state clearly why we don't want to use pre-generated keys.
I picked …

[#124488211] Add ADR for AWS credentials

---

docs/guides/upgrading_CF,_bosh_and_stemcells.md

Add a reminder to check Diego job ordering when upgrading CloudFoundry. We need to do this now that we are following [the job ordering in the Diego manifest](https://github.com/cloudfoundry/diego-release/blob/v0.1476.0/manifest-generation/diego.yml#L122-L424).
Read it. Make sure it makes sense.
Anyone but @alext or me.

[#115884129] Check diego job ordering

---

docs/team/dashboard_mac_mini.md

[#123828981 - Make Pingdom Dashboard Visible](https://www.pivotaltracker.com/story/show/123828981)
Update document on what is displayed on the Mac mini. Add details
of Pingdom dashboard and provide links to necessary documentation.
Read through it. Make sure it makes sense. 
Anyone but @timmow or myself

[#123828981] Add Pingdom dashboard details

---

docs/guides/spruce.md

Simply installing github.com/geofffranks/spruce via `go get` only
installs the library into the GOPATH.
In order to install a binary we need to specify the path containing
the main package, which for spruce is
`github.com/geofffranks/spruce/cmd/spruce`

Correct spruce install command

---

docs/team/orientation.md

The link to the Getting Started Guide was pointing at an old location.
Update to point at the current home.

Update link to Getting Started Guide

---

docs/team/orientation.md

This spreadsheet is now the canonical reference for what accounts a team
member *could* have and the URLs for accessing each one. By putting it in a
Google Doc we can be more comfortable about linking to semi-sensitive
information like our AWS account aliases. It will also become our reference
for starters and leavers, which should be more consistent than the Pivotal
Tracker tasks that we have at the moment.
1. Check that the words make sense.
1. Check that you can see the spreadsheet.
Not @dcarley

[#119991203] Link to spreadsheet as canonical accounts list

---

docs/team/working_practices.md

The names of the teams in github seem to have changed, so update the
documentation to remove a point of confusion.
Restaging of #54

Update the names of the teams

---

docs/team/working_practices.md

What
====
I spent a few minutes clicking around to locate this, but the URL is static so we can link it from the team manual.
How to review it
============
Check the manual still renders and the link is correct.
Who can review it
=============
Not @jonty.

Make it clear where to obtain the pivotal token

---

docs/team/dashboard_mac_mini.md

We have moved chrome plugin location in paas-cf. Update the link.
`mkdocs serve`, click on the link, should lead to correct destination
not me

Fix broken chrome plugin link

---

docs/architecture_decision_records/ADR443-ssl-only-for-applications-and-cf-endpoints.md
docs/architecture_decision_records/ADRXXX-hsts-preload-using-api-gateway.md

[#129039813 Implement HSTS Preload list requirements](https://www.pivotaltracker.com/n/projects/1275640/stories/129039813)
What
===
We want to serve only HTTPS for all endpoints and implement HSTS preload. Include 2 ADRs to describe the decisions taken:
* Add ADR for HSTS preload using AWS API Gateway
Describe the decisions taken to implement HSTS preload responder running on
AWS API Gateway and Cloud Front.
* Add ADR for SSL only for all endpoints
Document the decision of only serve HTTPS/SSL connections to any public
endpoint, for deployed applications or PaaS services.
How to review?
-----------
Read it, check if it makes sense
Who?
---
Anyone but @keymon

[#129039813] Add ADR for SSL only policy and HSTS preload implementation

---

docs/guides/common_support_tasks.md

We've not been documenting how to carry out some common support tasks, so this introduces a new guide for them. For now it just covers changing a users password.

Add guide for common support tasks

---

docs/team/dashboard_mac_mini.md

This will make it easier to generate the dashboard URL with some exported variables.
I suggest that the users store the credentials using pass:
```
pass insert -m github_creds <<EOF
export GITHUB_API_TOKEN=<your github access token>
export GITHUB_GDS_API_TOKEN=<your github.gds access token>
EOF
```
And then load then with:
```
eval $(pass github_creds)
```

Add a easy command to generate the PR wall board url

---

docs/guides/common_support_tasks.md
docs/team/responding_to_aws_alert.md

What?
----
We send our AWS notifications for the different accounts
to some mailing lists in Google Groups.
This commit documents this fact and links it to the common
support tasks.
How to review?
-----------
Render the docs as described in README.md. Do read-proofing
Who?
---
anyone but me

Document AWS notification mailing lists

---

docs/team/platform_alerting.md

In playing
https://www.pivotaltracker.com/n/projects/1275640/stories/131355243 we
added new groups to send alerts to.  This is where they are.

Document the new paas-alerts-{dev,ci,staging,prod} groups

---

docs/team/working_practices.md

This page is quite large, so adding a table of contents at the top helps
with navigation.

Add a TOC to the working practices page.

---

docs/team/dashboard_mac_mini.md

We've introduced a new dashboard, and also decided on using
`frame-splits` if we need to display split-screen dashboards.
Check the docs make sense.
Review with https://github.com/alphagov/paas-cf/pull/587

[#132736941] Update mac-mini docs to mention smashing

---

docs/guides/common_support_tasks.md

Currently it lives in google docs.
We want to eventually move it to the team manual, we're tracking that in
https://www.pivotaltracker.com/n/projects/1275640/stories/127987443
We'll need to make sure existing editors are happy with git before we move it,
so just link for the moment.

Add link to the paas support manual

---

docs/team/working_practices.md

- Mention signoff involves checking story is in production
- Remove Tech Lead and Tech Arch commenting on story as this does not
happen
- Mention we may delegate at standup if the board is blocked

Some tweaks to signoff process

---

docs/js/fix_search.js

MkDocs and Readthedocs don't currently agree on how to do search.
This means that search has poor UX on the publically deployed docs
on readthedocs.io.
Here's a workaround suggested in github comments that we could use
to fix things for us while we wait for the two projects to reconcile.
See:
https://github.com/rtfd/readthedocs.org/pull/2289
https://github.com/rtfd/readthedocs.org/issues/1088
See also https://github.com/alphagov/paas-developer-docs/pull/32
Should we use this fix?

Work around broken search integration

---

mkdocs.yml

Although the js was already included running `mkdocs serve` locally,
it was not included on readthedocs.io
Perhaps this config option is what we need:
http://www.mkdocs.org/user-guide/configuration/#extra_javascript

Include js fix for search in `extra_javascript`

---

docs/js/fix_search.js

We assumed the called function was provided by mkdocs/readthedocs,
but it is not.
Instead, we can hardcode to use the `latest` version, which should
be OK for long enough for us to switch away from mkdocs.

Fix js used to fix search

---

docs/team/managing_aws_access.md

Mostly to describe the temporary credentials scheme we are introducing.
See https://www.pivotaltracker.com/story/show/126126973
Also as a home for future details on IAM and access control.

Add doc on AWS access management

---

docs/guides/common_support_tasks.md
docs/team/notifying_tenants.md

We've been doing this for a while, it's time we wrote it down.
This process will hopefully be superseded fairly soon, but now
we have a home for docs as the process is iterated.

Document manual process for emailing tenants

---

docs/guides/upgrading_CF,_bosh_and_stemcells.md

Story: [Upgrade cflinuxfs2 stack](https://www.pivotaltracker.com/story/show/136187337)
The stack was recently upgraded because of CVEs. We should keep track of the stack as part of our standard CF upgrade process.
Not me

[#136187337] Mention stack release in CF upgrade

---

docs/team/dashboard_mac_mini.md

There is no Pivotal story for this as it is a quick and dirty support task.
Remove some jargon, update to say we don't display Pingdom status page
anymore (but it is still available), and add a section on the use of
Automator to open the browser upon login.
Read through and check it makes sense.
Anyone but me.

Update dashboard Mac Mini documentation

---

docs/team/managing_aws_access.md

Following an update to the script, this is no longer included in the
filename.
This should be reviewed along with https://github.com/alphagov/paas-cf/pull/709

Remove DEPLOY_ENV from sts token filename.

---

docs/architecture_decision_records/ADR0015-end-to-end-encryption.md
docs/architecture_decision_records/ADR009-x-forwarded-headers.md

Story: [How do encrypt traffic between the elb and gorouter using haproxy](https://www.pivotaltracker.com/story/show/136783629)
https://github.com/alphagov/paas-cf/pull/713 and
https://github.com/alphagov/paas-haproxy-release/pull/8 encrypt the traffic between the router ELB and HAProxy.
The ADR is updated to reflect the change.
Not @keymon or me

[#136783629] Update ADR009

---

docs/team/cf_security_rss.md
docs/team/responding_to_security_issues.md

Story: [Review & improve CF CVE notifications](https://www.pivotaltracker.com/story/show/136550911)
Doc to create the CF security datadog integration and updates to the "responding to security issues".
Not me

[#136550911] Doc to create the CF security datadog integration

---

docs/architecture_decision_records/ADR015-rds-storage-encryption-plans.md

[#136725001 Enable at rest encryption for broker created RDS DB instances](https://www.pivotaltracker.com/story/show/136725001)
What?
----
We want ot enable encryption in the instances from RDS broker, but due
the AWS limitations with the VM size and enabling encryption only on
creation, we must limit to some specific plans.
Added ADR with the decision.
How to review
-------------
Read, check that makes sense
Who?
----
Anyone but @keymon

[#136725001] Add ADR for decision of RDS plans with encryption

---

docs/team/notifying_tenants.md

Story: [Improve incident comms](https://www.pivotaltracker.com/story/show/136435555)
Detailed instructions for notifying tenants, especially in case of an incident.
Not me

[#136435555] Notifying tenants

---

docs/guides/common_support_tasks.md

In https://gaap.deskpro.com/agent/#app.tickets,t:3627 we discovered that
someone who was the sole org manager for a trial organisation had left that
organisation.
Documenting what we decided to do in this and future cases.
Anyone who does support, apart from me
- Is it clear what to do?
- Does @urmishah or Jess agree with the process?

How to deal with uncontactable org managers

---

docs/architecture_decision_records/ADR018-rds-broker-restore-last-operation.md

[#139361587 rds-broker: Able to create a instance from the latest snapshot of other instance](https://www.pivotaltracker.com/n/projects/1275640/stories/139361587)
What?
----
Add ADR016 to explain the usage of `LastOperation` and AWS tags to keep track of the sequence of operations to restore a RDS instance meanwhile keeping the rds-broker stateless.
How to review it?
-----------------
Read it and appreciate the style and beauty of the article.
Who?
----
Anyone but @keymon

[#139361587] ADR016: use of LastOperation during RDS restore

---

docs/guides/upgrading_CF,_bosh_and_stemcells.md

New releases can introduce new passwords or different uses of existing
passwords. It's possible that these may not be easy to rotate without
causing downtime. We'd like to know if this is the case before we next need
to use the credential rotation in anger (e.g. leaked secrets).
This was originally part of a follow-up story but I've pulled it out after a
discussion in knowledge share because we're likely to do one or more CF
upgrades before we play the follow-up to rotate more credentials.
Confirm that:
- new text makes sense
- is in an appropriate place in the guide
- is a sensible thing for us to do.
- the link to another page in the team manual works
I'll remove the documentation part from the story when merged.
Not @dcarley

[#140553003] Test rotating credentials when doing CF upgrades

---

docs/guides/upgrading_CF,_bosh_and_stemcells.md

What?
----
We want to add some notes about how to notify tenants after a CF upgrade.
Include reference to the generate_buildpack_release_notes.sh script added in https://github.com/alphagov/paas-cf/pull/829
How to review?
---------
Read it, check that makes sense :)
Who?
----
Anyone but @keymon or @csaliceti

[#139179971] Add a note to notify tenants after upgrade

---

docs/guides/upgrading_CF,_bosh_and_stemcells.md
docs/team/notifying_tenants.md

Story: [Upgrade CF to >= v252](https://www.pivotaltracker.com/story/show/139179971)
The CF upgrade notification part was added earlier to the upgrade section. It was decided it makes more sense to move it to the notification page.
Does is make sense?
Not me

[#139179971] Move upgrade notification to the relevant page

---

docs/guides/cf_admin_users.md

A workaround will be required to login to admin accounts. Update the team manual to enable people to find the workaround to login easily.
Ensure the meaning is clear. I have tested the instructions myself in the course of reviewing alphagov/paas-cf#830
If you like you may delay merging this change until alphagov/paas-cf#830 is merged, as the instructions won't work until that's been rolled out. However it seems unlikely that anyone will read them before we do roll it out anyway.
A team member who is not me

[#136027405] update team manual with google login workaround details

---

docs/team/deskpro.md
docs/team/pagerduty.md

Story: [Set up emergency email for tenants to use when alerting us OOH](https://www.pivotaltracker.com/story/show/137700363)
* Pageduty emergency service setup
* New "Deskpro" section. Only the setup for emergency is documented. The basic setup should be added later on
* Does it make sense?
* Do links work?
* Is the real setup the same as described?
Not me

[#137700363] Describe manual setup for emergency support

---

docs/architecture_decision_records/ADR003-AWS-credentials.md
docs/team/dashboard_mac_mini.md
docs/team/orientation.md

It moved to a "real" hostname with a real certificate on the evening of
2017-05-11 as described in this announcement:
- https://sites.google.com/a/digital.cabinet-office.gov.uk/gds-internal-it/github-enterprise-change-5-30pm-6pm-11th-may-2017/githubdigitalcabinet-officegovuk
Code review only.
Not @dcarley

[#145266177] Update the URL for GitHub Enterprise

---

docs/guides/common_support_tasks.md

We're no longer using the `rotate-user-password.sh` script to achieve
the result. It is worth to keep the documentation up to date, for future
reference from both new team members or the ones that have forgotten the
practice.
- Read through the docs
- Optionally, follow these to achieve the goal.

[SUPPORT] Correct the user password rotation docs

---

docs/team/statuspage.md

As we have just started using statuspage.io, this is some initial
documentation to aid in getting started and some knowledge transfer.
There are notes for future enhancements to the page.
Read the docs :) Feel free to login to statuspage and verify
Not me

Adds statuspage.io documentation to the manual

---

docs/support/responding_to_alerts.md

Add information about how to respond to the "CDN broker healthy" alert
because the DataDog monitor doesn't currently tell you much.
Check the content. Double check that the title/anchor matches the one used by alphagov/paas-cf#934
Anyone

[#145037767] Responding to alerts: CDN broker healthy

---

docs/support/escalation.md
docs/support/roles_and_responsibilities.md
docs/support/support_manual.md

Split out roles and responsibilities into separate doc. Others such as
‘useful links’ could also be pulled out into their own pages.
Known issues:
* Monitoring section is incomplete
* Link to ‘escalations’ hasn’t been put in because don’t know how to do
anchors
*The table is horrible
* weekend 9-5 working can’t be greyed-out
* support tickets section was due a rewrite

First adding of GDoc content

---

docs/team/working_practices.md

This is to reflect the fact we now sign merges into master on the
paas-bootstrap repository as well as paas-cf. Also, the GPG additions
to the git Concourse resource have long since been accepted upstream,
so we don't need to reference our old fork.
* Check the links work.
* Review in conjunction with https://github.com/alphagov/paas-bootstrap/pull/73.
Anyone but me

[#137364635] Update pull request merging guidance

---

docs/support/support_manual.md
docs/team/notifying_tenants.md

Changed docs to show that we now use Statuspage.io to send incident comms. This changes is in the [If you're incident comms:](https://government-paas-team-manual.readthedocs.io/en/latest/support/support_manual/#if-youre-incident-comms) section. 
Also edited the [Notifying Tenants](https://government-paas-team-manual.readthedocs.io/en/latest/team/notifying_tenants/)  section of the team manual to highlight the fact that we have two separate comms channels: one for incident (Statuspage) and one for updates and new features (Google group)>
Read the above sections of the team manual.

[#147123069] Changed process for incident comms

---

docs/team/orientation.md

Update link to credentials repo
It has been moved to GitHub.com
1. Check the new link works.
1. Check that I have't missed any other links.
Anyone.

[#145672449] Update link to credentials repo

---

docs/guides/cf_admin_users.md

This is no longer necessary now that we are using uaa-release v41.
Review in conjunction with https://github.com/alphagov/paas-cf/pull/971
Wait until https://github.com/alphagov/paas-cf/pull/971 is merged and deployed to CI and try to log into CI with your user account. Don't bother trying to test it in dev because it is a faff.
Only those with a CF admin user account associated with their GDS email address.

[#145682111] Remove UAA SSO workaround guidance

---

docs/support/support_manual.md

Make it clearer that email being sent is for GaaP, but status page is
now for tenant comms.

Clarify the channels for comms

---

docs/team/orientation.md

Standup has been at 9:45am for at least 4 weeks (since I started.) The manual still says it is at 9:30am and this corrects the time.

Update standup time to be 9:45am

---

docs/support/support_manual.md

With the removal of CI the link to the framesplits dashboard needs
updating within the support manual  to reflect us having one less environment.
Code check and local preview
Anyone but @LeePorte

Update link in to all pipelines dashboard

---

docs/guides/Connecting_to_Concourse_and_BOSH.md

Ordinarily we run `bosh` commands from a task running in Concourse, using `paas-cf`'s `make bosh-cli`. We want instructions ready for connecting to BOSH if this approach doesn't work, for instance if we're shaking Concourse. Until now instructions like this have lived in the `paas-cf` `README.md` but it's grown unwieldy. 
This PR creates a guide in the team manual for connecting to BOSH, both for running `bosh` CLI commands and by SSH. The incidents cover a range of potential difficulties:
* How to SSH or bosh-cli if Concourse tasks are unusable
* How to SSH or bosh-cli if the Concourse VM is unusable
* How to SSH or bosh-cli if we cannot create new VMs
* Perform the steps given in this new guide. Check you understand the instructions and they're effective in your environment. 
* If you …

[#145189815] New guide to connecting to Concourse and BOSH

---

docs/support/responding_to_security_issues.md

Update stemcell Guidance
Stemcell upgrades are quite safe and it is good practice to apply the
stemcell upgrade while triaging the CVE. If the update applies cleanly
there is no reason we shouldn't upgrade the stemcell
Check this makes sense, comment on if you think the split of stemcell upgrades and other security issues works
Anyone but me

Update guidance on stemcell upgrades

---

docs/team/dashboard_mac_mini.md

Our team no longer uses GitHub Enterprise.
Check the rationale and that the words still make sense.
Anyone.

Remove GitHub Enterprise from dashboard docs

---

docs/guides/Connecting_to_Concourse_and_BOSH.md

In approval @alext found that `bosh ssh` did not work because its SSH
connections were happening from outside of the VPC and were blocked by
our security rules.
The ideal fix would be to change our `ssh` commands to setup a SOCKS
proxy and use `BOSH_ALL_PROXY` as described by
https://bosh.io/docs/cli-tunnel.html. However this is only available on
bosh_cli V2 and we are on V1.
With that convenient approach ruled out, in this commit we add
instructions for manually specifying a gateway in a `bosh ssh` command.
* Check you understand these new instructions
* Check you can use them for both the "Connecting bosh_cli to BOSH" backup methods
Not @46bit @timmow @henrytk

[#145189815] Backup instructions for using `bosh ssh`

---

docs/support/responding_to_alerts.md

As we've upgraded concourse to the version that has supposedly fixed
this issue, we no longer need to document the process of fixing the
concourse volumes.
Sanity check would be enough.

[#150512756] Remove BTRFS process documentation

---

docs/support/finding_activity.md

We have enabled gorouter logs. This adds a short not to the manual about
which component name to search for and how to filter status codes.
Requires [paas-cf PR488](https://github.com/alphagov/paas-cf/pull/488/) to be deployed first.
Proofread should be enough
Not @chrisfarms nor @samcrang

[130899727] Add info about filtering gorouter logs

---

docs/team/orientation.md

We've changed the way we do both of these meetings, this PR makes the manual reflect our actual practices:
- Retro now uses a trello board for suggestions and to record actions
- Show & tell is now called Knowledge share
- Because it's no longer called show & tell we no longer need to point out
that it's not for external people
- We no longer vote on stories, we use a trello board for suggestions
Eyeballing the diff is fine. I've previewed the output in `mkdocs serve` already.
Anyone but @bleach

Update retro and knowledge share meetings

---

docs/guides/Tenant_Application_Penetration_Testing.md

Tenants will require penetration testing their applications. In order to do this we may have to notify AWS. These instructions outline the information required in a request and provide some one-liners to gather data.
- Make sure it reads okay.
- Make sure the one-liners run and generate sensible output.
- Make sure the assumptions and open questions in the PT seem reasonable.
Anyone but me. Probably someone who has submitted a pen testing request to AWS

[#150041160] Add instructions for submitting pen test requests

---

docs/guides/Restoring_the_CF_databases.md

To improve our knowledge of operating the platform, we wanted to practice restoring platform databases from snapshots. From this work we've written a new guide that can be used to restore tables, databases or entire platform RDS instances. We do not have particular incidents in mind that would use this information and thus kept the guide quite generic.
Attempt to use the new documentation to restore your dev environment from data-loss situation(s). We don't have a particular scenario in mind, so I suggest thinking situation(s) that could happen and seeing if you can fix them.
Not @46bit @henrytk.

[#149929492] Documentation on restoring CF databases

---

docs/support/responding_to_alerts.md

It's not very explicit that we should contact our users when their RDS
instance experiences failure events from AWS.
We're slightly reforming these sections to reflect that in a better
manner.
Read through the docs and see if the changes make sense.
Establish whether it's implying the need of contacting our tenants on occasion.

[#147674123] Extend process for dealing with RDS failure

---

docs/support/responding_to_alerts.md

The one liner previously provided would return space managers only. It
may be more beneficial to obtain Organisation, Space, Instance Name and
Org Managers in order to communicate with our tenants without causing
confusion.
- Check if the text make sense.
- Attempt to run this script following the instructions based (part of alphagov/paas-cf#1077)

[#147674123] Document the use of custom script

---

docs/support/responding_to_alerts.md

In case we need to respond to an incident caused by API Latency, we
would prefer to have a set of procedures in place to prevent us from
wasting time and look for the previous occurrences in Pivotal Tracker.
- Check if the content makes sense
Neither @camelpunch nor myself.

[#152150279] Describe API Latency procedures

---

docs/guides/Connecting_to_Concourse_and_BOSH.md
docs/guides/IPSec_debugging.md
docs/guides/Restoring_the_CF_databases.md
docs/support/responding_to_alerts.md

We now SSH to Bosh directly, so we can remove all instructions relating
to going via Concourse. We remove all of the backup options, because if
the Bosh VM isn't available then we have bigger problems than how to
use the Bosh CLI.
Review in conjunction with https://github.com/alphagov/paas-bootstrap/pull/100 and https://github.com/alphagov/paas-cf/pull/1100
Probably best to merge this after those ones, as things could change as a result of the review.
* check it is accurate
* check it reads most goodly, with grammar correctly and stuff.
* run it locally using instructions in the README. Check it looks okay and functions properly.
* preferably run all instructions that have changed to see they still work.
Anyone but me or @camelpunch

[#150711834] Update Bosh SSH instructions

---

docs/guides/Restoring_the_CF_databases.md

@alext [discovered a broken link](https://github.com/alphagov/paas-team-manual/pull/148#pullrequestreview-77093770) in docs that describe how to use point-in-time. It was linked to a screenshot during the writing process but this was removed because the documentation was too lengthy. It was shipped broken. This commit removes the broken link.
Code review should suffice.
Not @46bit

Fix broken link

---

docs/support/finding_activity.md

We are removing Nginx now that UAA is behind gorouter and the endpoint
blocking can be done within UAA.
We no longer have access logs from the UAA VMs in Logsearch. We do have
access logs from gorouter, which will help us to see traffic but not
necessarily diagnose inter-VM problems.
I've confirmed that the `uaa.audit.remote_address` in UAA's audit logs still
has the correct IP from `X-Forwarded-For`.
Review with alphagov/paas-cf#1104 and confirm that the changes make sense.
Not @dcarley or @bandesz.

[#152543946]: Remove references to Nginx in front of UAA

---

docs/architecture_decision_records/ADR022-web_app_language_and_framework_selection.md

Add an ADR saying that we'll use Ruby and Rails for user-facing apps that have a web interface.
* Check the ADR makes sense.
* Run the site as described in the README and verify it renders correctly.
Not me.

[#152517955] Add ADR for selection of language/framework for web apps

---

docs/architecture_decision_records/ADR017-cell-capacity-assignment.md
docs/architecture_decision_records/ADR021-cell-capacity-assignment-2.md

Replace ADR017 which has been very successful in ensuring that we didn't run out of capacity in the early days, but nowadays results in us over-provisioning infrastructure.
- Have a look at the rationale and see if it makes sense
- Check my [numbers in Datadog](https://app.datadoghq.com/notebook/20341/Cell%20capacity%20November%202017)
- Think of sanity checks of your own 
Anyone but @bleach and @tomskerous

Replace cell capacity planning method defined in ADR017

---

docs/support/responding_to_alerts.md

Add information to the manual to help support folk deal with intermittent ELB node failures.
Read it, try the links, check that the Datadog link would work (see corresponding [PR in paas-cf](https://github.com/alphagov/paas-cf/pull/1127)).
Not @chrisfarms or @camelpunch

Instructions for responding to ELB node failures

---

docs/guides/Github_oAuth_in-Dev.md

This commit adds a guide for how to enable Github oAuth in dev
environments. This method is not currently the default authentication
mechanism.
Code review
Pull this branch and run `pip install -Ur requirements.txt` followed by `mkdocs serve` visit http://127.0.0.1:8000
Test the how to guide
Not @LeePorte

Add how to for enabling Github oAuth in dev

---

docs/support/responding_to_alerts.md

Related to https://github.com/alphagov/paas-cf/pull/1148
Add details about where the invalid cert alert comes from, and how to
get more info from paas-metrics logs.
There is documentation in paas-cf about issusing new certs we link to it
here so people following the link from datadog can dig it out quickly.
* Check speeling
* Check links
* Check sanity
Not @chrisfarms

[#142503647] Add help for dealing with invalid cert alerts

---

docs/support/responding_to_alerts.md

We want to add information on what to do when we see various Trusted
Advisor warnings. We also intentionally manually exclude several Trusted
Advisor warnings and want to document why it's ok to expect/exclude
them.
We expect to have automated monitoring for Trusted Advisor in the not to distant future so adding this to the responding to alerts section made the most sense.
* Proof reading
* Check it renders ok
Not @keymon or @chrisfarms

[#153629133] Detail expected/excluded Trusted Advisor warnings

---

docs/architecture_decision_records/ADR015-rds-storage-encryption-plans.md

AWS have [enabled encryption support for t2 instances](https://aws.amazon.com/about-aws/whats-new/2017/06/amazon-rds-enables-encryption-at-rest-for-additional-t2-instance-types/) since this ADR was written. This therefore adds an update making this clear.
I've also fixed some a formatting issue.
Run the docs locally as described in the README. Verify this looks correct.
Not me.

Update ARD015 now that AWS support encrypted t2 RDS instances.

---

docs/support/finding_activity.md

After updating the syslog-release the @source.name field will only contain the BOSH job name. You can identify the VM with the @source.id field which contains the VM id.
Read it.
Not @LeePorte or @bandesz

[#134014357] Replace @source.name with @source.id

---

docs/team/working_practices.md

The team manual seems to reflect an older process where a single Product Manager would approve stories. This change updates the manual to reflect the current process where almost any team member can approve.
Also, adjust work-in-progress limits to match those of Rubbernecker.
It's confusing for new / prospective team members to read about a process that we don't use.
@camelpunch

Describe current process for story approval

---

docs/guides/upgrading_CF,_bosh_and_stemcells.md

Replace references to cf-release with cf-deployment, and adjust copy to suit.
It's a minimal change that seems to fit the approach we're using whilst we transition to cf-deployment. We expect the processes to change when / if we make it to cf-deployment. For example, we may use ops files to modify the cf-deployment.yml file in the future, relieving us of the burden of matching component release numbers to releases of cf-deployment.
We want to keep this document up-to-date in case people get confused and start using cf-release again (?)
Read the changes. See them in a browser using the instructions in the README.
@camelpunch nor @LeePorte

[#154769249] References to cf-release become cf-deployment

---

docs/support/responding_to_alerts.md

This PR adds methods for investigating and dealing with high latency alerts
to the team manual. I expect that this section should be uexpanded upon
after team discussion.
Checkout this branch and run `mkdocs serve` then visit http://127.0.0.1:8000/support/responding_to_alerts/ to make sure the content renders properly and makes sense.
No @LeePorte

[#120268519] Monitoring gorouter latency

---

docs/guides/Restoring_the_CF_databases.md

[#155463709 Migrate Spruce `grab` to bosh variables](https://www.pivotaltracker.com/story/show/155463709)
What?
----
In alphagov/paas-cf#1249 we have flatten the variables from
cf-secrets.yml to follow the convention `secrets_<name>`.
We update the manual runbooks to reflect this
How to review?
----------
Code review
Who?
----
Anyone but @keymon

[#155463709] Use secrets_ instead of secrets. for cf-secrets.yml

---

docs/guides/CF_UAA_user_management.md

I had to look these up from this story:
- https://www.pivotaltracker.com/story/show/150082611
While working this support ticket:
- https://gaap.deskpro.com/agent/#app.tickets,inbox:all,t.o:12383,vis:7
Having the instructions in the team manual should make them easier to
find because that's where I tried looking first.
The sub-shell and pipefail is required on the last command because
`uaac` can timeout our access token without writing to STDERR and the
subsequent pipes will get no results as if there were no users.
Check it makes sense and renders correctly.
Anyone.

[support] Add details about Global Auditor role

---

docs/architecture_decision_records/ADR013-building-bosh-releases.md
docs/styleguides/concourse_pipeline.md
docs/team/orientation.md

The website has moved to a new domain after the old domain as hijacked:
- https://www.cloudfoundry.org/blog/cve-2018-1227/
Check that the domain matches the advisory and that I haven't missed any occurrences.
Anyone.

[support] Replace concourse.ci domain in docs

---

docs/support/finding_activity.md

In updating to use blackbox in alphagov/paas-cf#1298 we can no longer
identify/tag the separate types of logs from gorouter. Access logs will
continue to be parsed and you can filter them based on their additional
fields, but the other log types will be unparsed and available from the
same `@source.component:gorouter` query.
Review with alphagov/paas-cf#1298
Anyone.

[#156302820] gorouter logs are under a single @source.component

---

source/index.html.md.erb

This fixes a mistake of mine from Firebreak week. See commit message.
Code review or preview in a browser (`bundle exec middleman server`).
Not @46bit

Reposition the Styleguides under the Guides

---

config.rb
config/tech-docs.yml
source/google52ece46ed12b8c21.html

We want to use a Google site-scoped search box on this site. For that to work we need Google to index it.
This also adds a google site verification file so that it can be added to the Search Console
* Run this locally
* Verify that there is no `<meta name="robots" content="noindex">` tag in the `<head>`
* Verify that `http://localhost:4567/google52ece46ed12b8c21.html` returns the file.
Not me.

[#156658598] Allow google to index the site.

---

config/tech-docs.yml

Using a [custom domain](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) avoids issues with some internal links that
linke between sections and therefore have to use an absolute path. When
deployed on the alphagov.github.io domain, Github Pages adds a
paas-team-manual path prefix, which breaks these links. The link checker
doesn't pick these up as broke because the prefix doesn't exist when
building/viewing locally.  Using a custom domain avoids the need for
this prefix.
* Build locally ('bundle exec middleman build`)
* Verify that absolute links use the correct hostname
https://github.com/alphagov/paas-aws-account-wide-terraform/pull/124 must be merged and applied, and Github Pages must be configured accordingly before this is merged.
Not me

[#156658598] Update to use a custom domain

---

source/CNAME

When you configure a Custom Domain in the repo settings, Github actually
adds a commit with a `CNAME` file to the gh-pages branch. Because this
wasn't present in the source, each deploy was removing this file which
removed the custom domain for the site. This isn't mentioned on the main
github docs for custom domains[1], but it is mentioned in the
troubleshooting section[2].
[1]https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/
[2]https://help.github.com/articles/troubleshooting-custom-domains/#github-repository-setup-errors
* Build the site (`bundle exec rake build`)
* Verify the `CNAME` file is added to the root of the build dir
* Verify it contains the bare hostname only.
Not me.

[#156658598] Add a CNAME file to set the Github Pages custom domain

---

source/team/rotating_credentials.html.md.erb

It's currently not safe to rotate CA certs - it causes downtime.
Read, check it makes sense.
Not me.

Add warning around rotating CA certs.

---

Gemfile
Gemfile.lock

These were defaulting to "GOV.UK Documentation" on all pages. With the
update to the gem, they now pick up the service name specified in
config/tech-docs.yml.
* Run locally (`bundle exec middleman serve`)
* Verify the page `<title>`s are now saying "PaaS Team Manual"
* Verify it still looks ok.
Not me.

Update govuk_tech_docs gem to fix page titles.

---

source/architecture_decision_records/ADR025-service-plan-naming-conventions.html.md.erb
source/index.html.md.erb

We want to be consistent with the naming of our service plans and make
it easier to introduce new plan names for different versions.
This ADR was the result of a [review of plan names](https://trello.com/c/mdu7HdyE/9-review-our-service-plans ) and a [proposal](https://docs.google.com/document/d/10f1_6Uzg6VcS60luYLK61Xa54-wpMhz8K-VyZwJzhw0/)
Make sure it makes sense, renders correctly
Not @chrisfarms

ADR025: plan naming conventions

---

source/support/incident_process.html.md.erb
source/support/responding_to_security_issues.html.md.erb

This commit updates the link used for contacting Information Assurance.
The link is to a newly created page with more information on it
including Out of Hours contact information.
Check the link is correct
Not @LeePorte

Update link for contacting Information Assurance

---

source/support/incident_process.html.md.erb
source/support/roles_and_responsibilities.html.md.erb

Update status page early before we know whether a reported issue is a incident.
The related templated was already created in Statuspage.
Read it and middleman it.
Not me or a middleman.

[#156946241] Update status page early before we know whether a reported issue is a incident

---

source/support/responding_to_alerts.html.md.erb

We have a Datadog monitor which will alert if any of the internal Cloud Foundry certificates will expire soon. We want to link to this section so the person on support will understand what the alert means.
Code review, middleman.
Not me.

[#154917736] Add notes about Cloud Foundry internal certificates to Responding to alerts

---

source/team/notifying_tenants.html.md.erb

Tom no longer works on the team. Refer to the people by their roles, so
that we don't need to update this for subsequent team changes.
Check the rationale and content.
Anyone.

Replace names of Product Managers with role

---

source/team/rotating_credentials.html.md.erb

Now that the referenced story has been played, this warning no longer
applies.
Verify it makes sense to remove this
Not me.

[#157032509] Remove warning about rotating CA certs.

---

source/support/support_manual.html.md.erb

The dashboard was removed in https://github.com/alphagov/paas-cf/pull/1159 in favour of a new Datadog dashboard, and that dashboard is visible on the Team's TVs/etc. I've updated this link to point to the new Datadog dashboard.

Update support manual link to Datadog summary

---

source/guides/Tenant_Application_Penetration_Testing.html.md.erb

When requesting pen-tests approvals to AWS we also shall send
the external IPs of our cluster (NAT instances, I guess) and the
RDS instances affected.
We assume that only the RDS instances for the given tenant org
will be affected.

Commands to get ext IPs and RDS DBs for pentest

---

.github/PULL_REQUEST_TEMPLATE.md
source/guides/upgrading_CF,_bosh_and_stemcells.html.md.erb

What
----
It looks like Middleman's markdown parser needs more space before the
third level indent for some reason, so the "main driver" bits were showing
at the second level instead of the third (see [the current output](https://team-manual.cloud.service.gov.uk/guides/upgrading_CF,_bosh_and_stemcells/#upgrading-cf-bosh-and-stemcells)).
I found the instructions for picking a version to be tricky to
understand - they seem to say "the latest version (only sometimes not
because they're broken (only even if they're broken you can just fix
them))" which seems overcomplicated. I've updated them to be more
opinionated about picking the latest stable release and fixing bugs in …

[#158938536] Simplify the docs on updating CF / fix formatting

---

source/.circleci/config.yml

This adds a dummy CircleCI config file to the source directory so that
it gets included in the gh-pages branch. This will prevent CircleCI from
running a v1.0 build on the gh-pages branch, and erroring because it
can't detect any tests.
How to review
-------------
It's not really possible to fully test this without merging to master (as that's where the `gh-pages` branch is built from). I tested as follows:
* I ran a `bundle exec rake build` to confirm that the circle config from the source directory gets included in the build.
* I created a test branch with this config to verify that the build gets skipped (see the `alext_test` build here: https://circleci.com/gh/alphagov/paas-team-manual)
Who can review
--------------
Not me.

Configure CircleCI to ignore gh-pages branch.

---

source/support/responding_to_alerts.html.md

What
----
We are no longer running our own ELK stack, as a result the links were
out of date. They have been corrected to the new links.
How to review
-------------
Code review and run locally with `bundle exec middleman server` and visit http://localhost:4567/support/responding_to_alerts/
Who can review
--------------
Not @LeePorte

[support] Update links to logging stack

---

source/team/notifying_tenants.html.md

What
----
We recently sent a new buildpack update email, but there weren't any
instructions on where to find the buildpack changes. This adds a brief
section to the manual where with some links to get you started.
How to review
-------------
Docs review
Who can review
--------------
Anyone

Add instructions for buildpack update emails

---

source/incident_management/incident_process.html.md
source/support/roles_and_responsibilities.html.md
source/support/support_manual.html.md
source/team/pagerduty.html.md

What
----
In #161212694 we moved our pagerduty account from gds-paas.pagerduty...
to governmentdigitalservice.pagerduty...
This PR updates the links in the team manual
How to review
-------------
Sanity check
Who can review
--------------
Anyone

[#161212694] Fix pagerduty links following rename

---

source/team/rotating_credentials.html.md

What
----
It's more convenient for an operator to be shown exactly which jobs to
run to rotate credentials, rather than them having to make an educated guess.
How to review
-------------
Doc review. 
Who can review
--------------
Anyone but I.

[#160506139] Make the CF credential rotation jobs and flow explicit

---

source/architecture_decision_records/ADR019-accessing-user-provided-services.html.md

What
----
We moved the documentation into the team manual because nobody could
find it. For some reason when I searched the team manual the only link I
found was this one, which was dead.
Let's point it at the right place :)
How to review
-------------
* :eyes: :computer:
Who can review
--------------
Not @richardTowers

[#SUPPORT] Fix dead link to VPC Peering docs

---

Gemfile.lock

To fix CVE-2018-16470 [1]. This isn't a significant thing for us as
this is a static site generator, so rack isn't running in production,
but it's worth updating to avoid the noise etc.
[1]https://groups.google.com/forum/#!msg/rubyonrails-security/U_x-YkfuVTg/xhvYAmp6AAAJ
How to review
-------------
Code review should be enough
Who can review
--------------
Not me.

Upgrade rack to 2.0.6

---

source/accounts/account_lifecycle.html.md
source/accounts/getting_data_about_trial_accounts.html.md
source/index.html.md

What
----
* Restructured the pages so there's just one page about the account
lifecycle.
* Added a section on creating new trial orgs as per [the draft in google docs](https://docs.google.com/document/d/12vAsFW1fhaFTj8oiukaz2agpbQ6r6tsRpCBYrkgtFzM)
How to review
-------------
* Brief copy review (it's already been looked at by James and me)
* Check the rendered output looks right in this demo: https://test-team-manual-for-james.london.cloudapps.digital (u: pirate p: bunting)
Who can review
--------------

[#160382631] Document process for tenants to begin trial

---

source/team/managing_aws_access.html.md

We now have the necessary config in place to support using assume-role
from the central gds-users account instead of needing individual users
in each account. This updates our docs to reflect this, and to link out
to the RE manual for how to set this up.
How to review
-------------
Review along with https://github.com/alphagov/paas-aws-account-wide-terraform/pull/139.
Check the new content makes sense and contains enough detail.
Who can review
--------------
Not me

Update AWS access instructions to use assume-role

---

source/guides/upgrading_CF,_bosh_and_stemcells.html.md
source/incident_management/incident_process.html.md
source/incident_management/responding_to_alerts.html.md
source/support/responding_to_security_issues.html.md
source/support/support_manual.html.md
source/team/dashboard_mac_mini.html.md
source/team/pagerduty.html.md
source/team/platform_alerting.html.md
source/team/statuspage.html.md

What
----
We are migrating away from Datadog to use Prometheus. This PR
updates the references and information that we have within the team
manual.
This needs to be done to ensure that the person on support has the right
information to hand in order to resolve issues in a timely manner.
How to review
-------------
Code review and run locally
Who can review
--------------
Anyone

[#162612712] Update Datadog to Prometheus

---

source/architecture_decision_records/ADR021-cell-capacity-assignment-2.html.md
source/architecture_decision_records/ADR023-idle-cpu-alerting-change.html.md

What
----
We're removing Datadog, so these no longer apply. Instead of updating
them to refer to the equivalent metrics in the new system, I've reworded
them to generally describe the thing being measured so that they're
agnostic of the metrics system being used, and therefore shouldn't need
updating again if this changes.
I've also added a link to ADR032 from ADR021 as it supersedes one detail of it.
How to review
-------------
Check the new wording makes sense.
Who can review
--------------
Not me.

[#162612712] Remove Datadog references from ADRs

---

source/index.html.md
source/support/finding_route_owners.html.md

What
----
During a previous incident it wasn't clear how to quickly find the org managers responsible for a particular route. This PR adds a guide into the support section on how to achieve this.
How to review
-------------
Run the branch locally and make sure the new content makes sense
Who can review
--------------
anyone

[#163860737] Add new route owner finding guide

---

source/guides/upgrading_CF,_bosh_and_stemcells.html.md

What
----
During CF upgrades, resource starvation of a dev environment can lead to
unexpected test failures. It's easy enough to resolve, but not obvious that it
happens.
How to review
-------------
1. Check the content
2. Check it renders correctly
Who can review
--------------
Anyone but me

[#163521334]Warn about resource starvation in dev during upgrades

---

source/incident_management/incident_process.html.md

What
----
The Tech writer review appears to have changed the meaning of this line - from "this may be the person on support, it now reads as "this must be the person on support"
I have restored the original meaning of the line
How to review
-------------
Read the new wording, and confirm it is equivalent to the original intention of the line.
Who can review
--------------
Not @tnwhitwell. May require tech writer 2i (@jonathanglassman)

Update incident process to restore original meaning

---

source/team/notifying_tenants.html.md

What
----
In #165643581 we added a new tool to `paas-cf` for extracting the email
addresses of tenants from Cloud Foundry, so that we could send emails to an
accurate list of tenants. In this commit, we add guidance to the team manual on
how to use the tool and send technical emails.
How to review
-------------
1. Copy review
2. Check it all renders properly
Who can review
--------------
It would be nice to have a @jonathanglassman opinion, otherwise paired on by @LeePorte and @AP-Hunt

[#165643581] Add guidance for sending technical emails to tenants

---

source/team/notifying_tenants.html.md

What
----
https://github.com/alphagov/paas-team-manual/pull/291 didn't specify which email address tenants should contact. Presumably it was intended to be filled in when sending the email. But in the vast majority of cases we'll want them to contact our support email address, and using that prevents forgetting to put a valid email address.
Who can review
--------------
Not @46bit

Use the support email address for notifying tenants

---

source/accounts/account_lifecycle.html.md

What
----
Following a conversation I had with Luke on Slack:
```
yes, the name is sufficient
and please make sure to mention the name of the org youve created in
your response
Richard Towers [2:43 PM]
Hi NAME,
Thank you for your request. I've created a new trial organisation for
you called ORG in our London region. You should get two
emails, one inviting you to create a an account, and one inviting you to
join our announcements mailing list.
Please let us know how you get on, or if you have any questions about
the service.
Thank you,
Richard
Look good to you?
luke.malcher [2:45 PM]
yes - and i see no reason why we couldnt make that a boilerplate email
*message
Richard Towers [2:45 PM]
yeah - it’s annoying having to type it out each time
:rolling_on_the_floor_laughing:
```
How to review …

Update account lifecycle with boilerplate email

---

source/team/rotating_credentials.html.md

What
----
The previous Certificate Authorities rotation instructions did not make completely clear that `rotate-cf-certs-leafs` had to be run first of all. This commit updates the instructions to ensure that people do run that in future.
These instructions need a bigger refactor. But with this update they do work.
How to review
-------------
Code review.
Who can review
--------------
Not @46bit

Clarify how to rotate Certificate Authorities

---

Gemfile
Gemfile.lock

What
----
The container being used to build and deploy the team manual was unable to
compile the native extension when installing mini_race 0.1.15. Version 0.2
works for us, is newer, and compiles in the container.
How to review
-------------
Check it compiles on Concourse
Who can review
--------------
Anyone

Update mini_racer to 0.2

---

source/incident_management/responding_to_alerts.html.md
source/index.html.md
source/team/managing_access_to_cloud_services.html.md
source/team/rotating_credentials.html.md

What
----
I have refactored the "Manage access to AWS" to be "Manage access to Cloud services" and added non-exhaustive info about
- Google Cloud
- Aiven
- Microsoft Azure
I have also added some very light documentation about rotating UAA SSO OAuth credentials.
How to review
-------------
`bundle install && rake build && (cd build && python -m http.server)`
`open http://localhost:8000`
Who can review
--------------
Not @tlwr

Update docs for cloud services and SSO

---

source/support/CF_UAA_user_management.html.md

What
----
Adds the PaaSmin user management page to the user management section
See https://github.com/alphagov/paas-admin/pull/344
How to review
-------------
Code review
Who can review
--------------
@LeePorte

Add PaaSmin user management page to user management section

---

source/support/zendesk.html.md

What
----
I want a tag for the cdn broker, but there isn't one at the moment. It would be better to have tags for the individual services we're using.
How to review
-------------
Check the tags
Who can review
--------------
Not @richardTowers , doesn't need 2i or comms approval since this is internal documentation.

Make Zendesk tags explicit about backing service

---

source/guides/upgrading_CF,_bosh_and_stemcells.html.md
source/team/notifying_tenants.html.md

What
----
We got this slightly wrong this time, as we didn't run
`./scripts/update_buildpacks.sh`, so we were missing dependency
information in the email.
Adding some documentation that isn't incorrect might help us avoid this
mistake in future.
How to review
-------------
* Review the docs
Who can review
--------------

Update our docs on sending buildpack emails

---

source/team/dashboard_mac_mini.html.md

What
----
We are migrating to a world where `make dev showenv` in `paas-cf` no longer spews secrets all over an operators screen. This commit tells readers to use the preferred `make <env> credhub` instead.
How to review
-------------
1. Copy review
Who can review
--------------
Anyone

[#168263529] make dev credhub is preferred over showenv

---

source/incident_management/incident_process.html.md.erb
source/support/roles_and_responsibilities.html.md
source/team/notifying_tenants.html.md

What
----
Updated the team manual to reflect 
- new incident management process
- new roles and responsibility to include Techops RE incident escalation
- Amended a broken link in notifying tenants page.  
How to review
-------------
Review the contents:
- All the link still work in the pages changed
- The headers are of correct level
- Generally double checking content and formatting are correct. 
Describe the steps required to test the changes.
Who can review
--------------
Anyone from the PaaS team.

Update new incident process and roles and responsibilities.

---

source/guides/common_support_tasks.html.md

What
----
We no longer deploy or use a `paas_user_testing` org, so this information was irrelevant. This commit removes it.
How to review
-------------
1. Code review
2. Check it still renders OK
Who can review
--------------
Anyone

Remove out of date information from common support tasks

---

Gemfile.lock
source/support/responding_to_security_issues.html.md

What
----
- Add NCSC webcheck as one of the issue sources in the "Responding to security issues" section. 
- Bump nokogiri from 1.10.5 to 1.10.8
How to review
-------------
Pull and check everything runs
Who can review
--------------
Anyone

Add ncsc web check & bump nokogiri

---

source/team/rotating_credentials.html.md

What
----
CVE-2020-5400 leaked the basic auth credentials of some our brokers. We played Pivotal Tracker story #171180051 to rotate those credentials. It added a new pipeline job. Unlike our other credential rotation processes this one involved downtime because our brokers lack support for changing basic auth credentials without downtime.
This commit documents the process so that we retain knowledge. I'm most keen to have documented what this new job doesn't do: it only rotates the basic auth credentials, not anything else. That is important context to retain.
How to review
-------------
Read through the documentation changes and see if you have all your questions answered.
Who can review
--------------
Not @46bit.

[#171180051] Document how to rotate broker passwords

---

source/team/notifying_tenants.html.md

What
----
We have a new flag available when fetching tenant email addresses that
targets only the org management users. This needed to be documented in
order to not be forgotten.
How to review
-------------
Make sure it renders and reads correctly
Who can review
--------------
Anyone

[#171978958] Add documentation of `MANAGEMENT` flag when fetching tenant emails

---

source/architecture_decision_records/ADR454-new-product-pages-language-and-framework.html.md
source/index.html.md

What
----
Document why and what we agreed for rebuilding the paas-product pages
How to review
-------------
[Rendered text](https://github.com/alphagov/paas-team-manual/blob/8ebca9645e1d7eaca324ac174c70f50ce330196c/source/architecture_decision_records/ADR454-new-product-pages-language-and-framework.html.md)
👀 and 🤔
Who can review
--------------
not me

ADR 454 for new product pages

---

source/accounts/account_lifecycle.html.md
source/support/zendesk.html.md

What
----
[We've moved support forms into paas-admin](https://github.com/alphagov/paas-admin/pull/936), so link urls need to be updated.
How to review
-------------
- check url takes you to the correct page
Who can review
--------------
not @kr8n3r

Update links to support & signup forms

---

source/guides/GPG.html.md

What
----
We use keyserver.ubuntu.com as our keyserver in
https://github.com/alphagov/paas-credentials/blob/master/Makefile#L18
and syncing isn't as fast as we'd like, so it makes sense to use the
same keyserver in both places.
How to review
-------------
Code review
Who can review
--------------
Anyone

Update GPG keyserver to `keyserver.ubuntu.com`

---

source/architecture_decision_records/ADR025-service-plan-naming-conventions.html.md
source/guides/Tenant_Application_Penetration_Testing.html.md
source/guides/upgrading_CF,_bosh_and_stemcells.html.md
source/team/comms_lead_role.html.md

What
----
Some heading levels were skipped (for example, H1s to H3s), which is an accessibility issue. I fixed them so that levels are no longer skipped.
How to review
-------------
Preview content locally and check that the fixes work and are appropriate
Who can review
--------------
Anyone but @cmcnallygds

Fix heading levels for accessibility

---

source/guides/common_support_tasks.html.md

What
----
Removed link to outdated team manual
How to review
-------------
Check that content looks OK and that there is no essential info in that team manual which is not replicated elsewhere
Who can review
--------------
Anyone familiar with this team manual and its content

Remove link to team manual

---

source/guides/test_alertmanager.html.md
source/index.html.md

What
----
Document how to test Alertmanager is hooked up to PagerDuty
How to review
-------------
Read the docs
_Rendered image_

guides: add guide on testing alertmanager

---

source/incident_management/incident_process.html.md.erb

What
----
I've checked and updated our guidance for in hours incident process and out of hours incident process.
I've mainly updated the comms lead sections - added points about setting up hangouts, and updated the link to the incident report template (we now use a newer one). Also added the lines about updating Xgov slack paas channel. The 1st para under 'Out of hours incident process' wasn't super clear, so i've tidied that up a bit. I did this to make it easier for comms leads and support engineers to understand what they need to do in the event of an incident.
How to review
-------------
Read through as if you've been asked to handle an incident, and check that:
- you would know whats expected of you (as a comms lead)
- links work and direct you to relevant docs/guidance
Who can …

Updated comms lead Incident Process guidance in our team manual

---

source/architecture_decision_records/ADR045-aws-waf.html.md
source/index.html.md

What
----
Adds ADR for enabling AWS DDoS Response Team access to to the WAF Logs and WAF API in order to mitigate DDoS attacks against the platform.
How to review
-------------
Read and make sure it makes sense
Who can review
--------------
Anyone

Add ADR to AWS DRT access to PaaS

---

source/support/responding_to_alerts.html.md

What
----
This PR adds a small summary of how to respond to DDoS attack alerts. It includes some PaaS-specific considerations, rough guidance for how we expect to respond, etc.
Having this guidance open to the public is a bit strange. But I anticipate that it isn't much use–all it really says is that we'll get AWS to help us, as they'd expect. An attacker could push the Team Manual website offline as well as attacking PaaS, but we'd still have these docs available in GitHub.
How to review
-------------
Read through and leave any comments.
Who can review
--------------
Not @46bit

[#175917080] Add advice on how to respond to DDoS alerts

---

source/guides/Github_oAuth_in-Dev.html.md

What
----
Concourse 7 changed so that dex sends the location of the redirect_uri to github
https://github.com/concourse/concourse/issues/6551#issuecomment-781622203
This means it has to match the callback url.
This needs to match what it is currently, which is fly/issuer/callback
How to review
-------------
Spin up the docs locally. And make sure that github auth works with the new url
Who can review
--------------

Update oauth docs for concourse 7

---

source/architecture_decision_records/ADR047-postgres-extensions-approach.html.md
source/index.html.md

What
----
Added ADR047 so that the next person to pick up a "release a new major postgres version to tenants" story will have a better clue what to do about extensions.
How to review
-------------
Read?
Who can review
--------------
Leadership I guess.

[#179620265] add ADR047 "Postgres allowed-extensions approach"

---

source/accounts/account_lifecycle.html.md

What
----
Replaces link to help with organisation names. Instead use https://www.gov.uk/government/organisations
The GOV.UK Register has been archived, so we cannot rely on it for naming
organisations.
Also typos
How to review
-------------
Read
Who can review
--------------
Anyone

Updates out-of-date org name instructions

---

source/support/tenant_elasticache_service_updates.html.md

What
----
Updates instructions so that they don't:
- reference alt-maintenance-window
- imply that you have to do the update outside of working hours
How to review
-------------
Check that it makes sense
Who can review
--------------
Anyone

Removes reference to alt-maintenance-window

---

source/support/responding_to_alerts.html.md

What
----
The guidance mentioned Lets Encrypt for certificates issued on behalf of the CDN broker, but we've used AWS Certificate Manager for some time now.
How to review
-------------
Copy review

Correct guidance about expiring CDN certs

---

source/support/responding_to_alerts.html.md

What
----
Add section describing actions to take if a diego cell's ephemeral disk usage is near full. We weren't able to diagnose the true cause of this because we let the issue fall out of our log retention, but the next person to encounter it would probably appreciate being told what action will make the immediate danger go away.
How to review
-------------
Read it.
Who can review
--------------
Anyone with taste.

responding to alerts: add section on cell disk usage being near full

---

source/guides/upgrading_CF,_bosh_and_stemcells.html.md

What
----
https://www.pivotaltracker.com/story/show/181997913
Updated the documentation surrounding buildpack upgrades now that the process has changed somewhat - we don't seem to have been *closely* following the submitter-reviewer pattern for a few cycles now.
Takes into account https://github.com/alphagov/paas-cf/pull/2894
How to review
-------------
:eyes: 
Who can review
--------------
Not @risicle

buildpack upgrades: document updated process

---

source/architecture_decision_records/ADR0048_add_resources_table.md
source/architecture_decision_records/ADR0049_calculate_bills.md
source/index.html.md

What
----
We made the decision to halt our plans for a new and improved billing engine. As part of the tidy up, we should mark the ADRs we wrote as deprecated.
How to review
-------------
1. Copy review
2. Does the strike through work on the index page?

[#181819839] Deprecate the ADRS for New Billing

---

source/guides/upgrading_CF,_bosh_and_stemcells.html.md

What
----
Previously, the fact we post them to Slack too was a little buried. Added it as
a distinct step to make that clearer.
How to review
-------------
1. Copy review
2. Make sure it renders OK
Who can review
--------------

Clarify where we should post buildpack upgrade announcements

---

source/incident_management/incident_process.html.md.erb

The old guidance was incomplete and not as helpful as it could be. This updated guidance gives a clearer path for engineers and people on comms support to follow in the case of an incident.
What
----
Replaced the old incident management guidance with a new workflow for engineers and comms support people.
How to review
-------------
1. Open locally and make sure the content displays correctly.
2. Check for accuracy.
Who can review
--------------
@AP-Hunt

Update incident management guidance

---

.github/workflows/deploy.yml

Description:
----
- Slack notification message on failure was previously empty as the event that triggers the workflow is no longer pull requests but merging into main
- The message now posts the commit SHA when a deployment fails
How to review
-------------
Code review.

185550872 - Fix Slack notification message

---

source/index.html.md
source/upcoming_plans/ireland_decomissioning.html.md

What
----
Add Ireland high level decommission plan for production
How to review
-------------
Read the changes.
Who can review
--------------
Any PaaS team member

Add Ireland high level decommission plan for production

---

source/guides/GPG.html.md

What
----
gpg-agent now ships with gnupg package: https://github.com/Homebrew/homebrew-core/commit/965e130e04e5900e35bf1f0b6ebad9d1c2f680a7
Also update name of MacOS
Who can review
--------------
Current PaaS team members

Update MacOS GPG installation instructions

---

source/incident_management/incident_process.html.md.erb
source/incident_management/roles_and_responsibilities.html.md
source/support/so_you_are_on_support.html.md
source/team/comms_lead_role.html.md
source/team/orientation.html.md
source/team/working_practices.html.md

What
----
PaaS Team Manual Technical documentation updated
How to review
-------------
Verify the changes as per the document attached in the ticket 
Who can review
--------------
GDS PaaS team lead or SRE.

187187231 - Update PaaS tenant facing documentation
